import { chromium, expect } from '/Users/tien/Developer/ChronoShift/node_modules/@playwright/test/index.mjs';
import {writeFile} from 'node:fs/promises';
const base='https://tien-lam.github.io/ChronoShift/';const source='aa99397c07b058447c4c18fa1c938ced4f09ba97';const worker='59be1f21293ff6c0';const start=new Date().toISOString();const entries:any[]=[];const errors:any[]=[];const requests:any[]=[];
const b=await chromium.launch({channel:'chrome'});const c=await b.newContext({locale:'en-AU',timezoneId:'Australia/Sydney',colorScheme:'dark',viewport:{width:1280,height:900}});const p=await c.newPage();p.on('pageerror',e=>errors.push({type:'pageerror',text:e.message}));p.on('console',m=>{if(m.type()==='error')errors.push({type:'console',text:m.text()});});p.on('request',r=>requests.push({url:r.url(),method:r.method(),postData:r.postData()}));await p.goto(base);
const release=await p.evaluate(async()=>await(await fetch('release.json',{cache:'no-store'})).json());expect(release.sourceCommit).toBe(source);expect(release.base).toBe('/ChronoShift/');const sw=await p.evaluate(async()=>await(await fetch('sw.js',{cache:'no-store'})).text());expect(sw).toContain(worker);const assets=await p.evaluate(()=>({scripts:Array.from(document.scripts).map(e=>e.src).filter(Boolean),styles:Array.from(document.querySelectorAll('link[rel="stylesheet"]')).map(e=>(e as HTMLLinkElement).href)}));expect(assets.scripts[0]).toContain('index-CEcLWwpD.js');expect(assets.styles[0]).toContain('index-BEANxCaz.css');await expect(p.locator('main')).toHaveAttribute('data-offline-ready','true',{timeout:30000});
const d=p.locator('#message');const target=p.locator('#target-zone');await target.fill('UTC');await d.pressSequentially('April 9, 2026 at 9:16pm UTC',{delay:35});await expect(p.locator('.hero-time')).toHaveText('9:16 pm');entries.push({event:'live incremental typing',at:new Date().toISOString()});await expect(p.getByRole('button',{name:'Convert',exact:true})).toHaveCount(0);await target.fill('Asia/Tokyo');await expect(p.locator('.hero-time')).toHaveText('6:16 am');await expect(p.locator('.result-date')).toContainText('10 Apr 2026');entries.push({event:'target change auto recomputes independently',at:new Date().toISOString()});await target.fill('UTC');await d.click();await p.getByRole('button',{name:'Clear',exact:true}).click();await expect(p.locator('.result')).toHaveCount(0);await p.waitForTimeout(700);await expect(p.locator('.result')).toHaveCount(0);entries.push({event:'clear remains empty',at:new Date().toISOString()});
await d.fill('April 9, 2026 at 12:34:56.789pm UTC');await expect(p.locator('.hero-time')).toHaveText('12:34:56.789 pm');
async function choice(id:string,value:string){await p.locator('#'+id).click();await p.locator(`.choice-item[data-value="${value}"]`).click();}
for(const theme of ['dark','light']){await p.getByLabel('Appearance',{exact:true}).click();await choice('theme',theme);await p.getByLabel('Appearance',{exact:true}).click();for(const width of [1280,390]){await p.setViewportSize({width,height:900});await expect(d).toHaveValue('April 9, 2026 at 12:34:56.789pm UTC');await expect(p.locator('.hero-time')).toHaveText('12:34:56.789 pm');await p.screenshot({path:`/tmp/chronoshift-live-adversarial/published-${theme}-${width}.png`,fullPage:true});const boxes=await p.evaluate(()=>{const r=(selector:string)=>{const e=document.querySelector(selector)!;const b=e.getBoundingClientRect();return {x:b.x,y:b.y,width:b.width,height:b.height,font:getComputedStyle(e).fontSize};};return {viewport:innerWidth,scroll:document.documentElement.scrollWidth,workspace:r('.workspace'),input:r('.input-panel'),result:r('.result-panel'),time:r('.hero-time'),copy:r('.copy-button'),help:r('#input-help')};});expect(boxes.scroll).toBe(width);entries.push({event:`layout ${theme} ${width}`,at:new Date().toISOString(),boxes});}}
const lifecycle=await p.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();return {controller:navigator.serviceWorker.controller?.scriptURL,active:r?.active?.state,waiting:r?.waiting?.state,scope:r?.scope,caches:await caches.keys()};});expect(lifecycle.controller).toBe(base+'sw.js');expect(lifecycle.active).toBe('activated');expect(lifecycle.scope).toBe(base);expect(lifecycle.caches).toContain('chronoshift-'+worker);await c.setOffline(true);await p.reload();await d.fill('April 9, 2026 at 6:27pm UTC');await expect(p.locator('.hero-time')).toHaveText('6:27 pm');await expect(p.locator('main')).toHaveAttribute('data-offline-ready','true');entries.push({event:'actual controlled offline reload then fresh live input',at:new Date().toISOString(),lifecycle});await c.setOffline(false);
expect(requests.filter(r=>!r.url.startsWith('https://tien-lam.github.io/'))).toHaveLength(0);expect(requests.filter(r=>r.postData||r.url.includes('April')||r.url.includes('6%3A27'))).toHaveLength(0);expect(errors).toHaveLength(0);const end=new Date().toISOString();await writeFile('/tmp/chronoshift-live-adversarial/publication-results.json',JSON.stringify({start,end,browser:b.version(),channel:'chrome',release,expectedWorker:worker,assets,lifecycle,entries,errors,requests},null,2));console.log(JSON.stringify({start,end,browser:b.version(),source,worker,entries:entries.length,errors}));await b.close();
