import {join} from 'node:path';
import {safeArchive} from '../../../../scripts/reuse-pages-artifact';
const runId=Bun.argv[2],mode=Bun.argv[3]||'reuse';
if(!/^\d+$/.test(runId||'')||!['reuse','fallback'].includes(mode))throw Error('run id / mode');
const dir=import.meta.dir,startedAt=new Date().toISOString(),commands:any[]=[];
const sha=(b:Uint8Array)=>new Bun.CryptoHasher('sha256').update(b).digest('hex');
async function command(args:string[]){const began=new Date().toISOString(),p=Bun.spawn(args,{stdout:'pipe',stderr:'pipe'});const [bytes,error,code]=await Promise.all([new Response(p.stdout).arrayBuffer(),new Response(p.stderr).text(),p.exited]);commands.push({args,began,ended:new Date().toISOString(),error,code});if(code)throw Error(error);return new Uint8Array(bytes);}
async function json(args:string[]){return JSON.parse(new TextDecoder().decode(await command(args)));}
const run=await Bun.file(join(dir,runId+'-run.json')).json(),jobs=await Bun.file(join(dir,runId+'-jobs.json')).json(),metadata=await Bun.file(join(dir,runId+'-artifacts.json')).json();
if(metadata.total_count!==metadata.artifacts.length||metadata.artifacts.filter((a:any)=>a.name==='github-pages').length!==1)throw Error('artifact inventory incomplete/ambiguous');
const artifact=metadata.artifacts.find((a:any)=>a.name==='github-pages');
const zip=await command(['gh','api',`repos/Tien-Lam/ChronoShift/actions/artifacts/${artifact.id}/zip`]);
if(artifact.expired||zip.length!==artifact.size_in_bytes||artifact.digest!=='sha256:'+sha(zip))throw Error('artifact digest or bytes');
const zipPath=join(dir,runId+'-pages.zip');await Bun.write(zipPath,zip);
const wrapper=new TextDecoder().decode(await command(['unzip','-Z1',zipPath])).trim().split('\n');if(wrapper.length!==1||wrapper[0]!=='artifact.tar')throw Error('wrapper');
const tar=await command(['unzip','-p',zipPath,'artifact.tar']),tarPath=join(dir,runId+'-pages.tar');await Bun.write(tarPath,tar);
async function inventory(path:string){const names=new TextDecoder().decode(await command(['tar','-tf',path])).trim().split('\n'),entries=new TextDecoder().decode(await command(['tar','-tvf',path])).trim().split('\n');if(!safeArchive(names,entries)||new Set(names.map(x=>x.replace(/\/$/,''))).size!==names.length)throw Error('unsafe/duplicate names');return await Promise.all(names.filter((_,i)=>entries[i].startsWith('-')).sort().map(async name=>{const bytes=await command(['tar','-xOf',path,name]);return {path:name.slice(2),bytes:bytes.length,sha256:sha(bytes)};}));}
const [files,ciFiles]=await Promise.all([inventory(tarPath),inventory(join(dir,'candidate-pages.tar'))]);
const release=await json(['tar','-xOf',tarPath,'./release.json']);
const root='repos/Tien-Lam/ChronoShift';
const [head,releaseTree,currentMain]=await Promise.all([json(['gh','api',root+'/commits/'+run.head_sha]),json(['gh','api',root+'/commits/'+release.sourceCommit]),json(['gh','api',root+'/commits/main'])]);
const token=Date.now().toString();
const publicFiles=await Promise.all(files.map(async file=>{const began=new Date().toISOString(),response=await fetch('https://tien-lam.github.io/ChronoShift/'+file.path+'?independent-audit='+token,{cache:'no-store'}),body=new Uint8Array(await response.arrayBuffer());return {path:file.path,began,ended:new Date().toISOString(),status:response.status,url:response.url,contentType:response.headers.get('content-type'),expectedSha256:file.sha256,actualSha256:sha(body),expectedBytes:file.bytes,actualBytes:body.length,matched:response.status===200&&sha(body)===file.sha256&&body.length===file.bytes};}));
const rootResponse=await fetch('https://tien-lam.github.io/ChronoShift/?independent-audit='+token,{cache:'no-store'}),rootBody=new Uint8Array(await rootResponse.arrayBuffer()),index=files.find(f=>f.path==='index.html')!;
const executedJobs=jobs.jobs.filter((j:any)=>j.conclusion!=='skipped'),prepare=jobs.jobs.find((j:any)=>j.name==='prepare'),deploy=jobs.jobs.find((j:any)=>j.name==='deploy');
const ciComparable=mode==='reuse'?ciFiles:ciFiles.filter(f=>f.path.startsWith('assets/')),pagesComparable=mode==='reuse'?files:files.filter(f=>f.path.startsWith('assets/'));
const result={startedAt,endedAt:new Date().toISOString(),runId,mode,commands,artifact:{metadata:artifact,zipSha256:sha(zip),tarSha256:sha(tar),zipBytes:zip.length,tarBytes:tar.length,files,release},ciComparable,pagesComparable,inventoryMatches:JSON.stringify(ciComparable)===JSON.stringify(pagesComparable),trees:{publishing:head.commit.tree.sha,tested:releaseTree.commit.tree.sha,currentMain:currentMain.commit.tree.sha,currentMainSHA:currentMain.sha},exactTree:head.commit.tree.sha===releaseTree.commit.tree.sha&&head.commit.tree.sha===currentMain.commit.tree.sha,run:{event:run.event,branch:run.head_branch,head:run.head_sha,conclusion:run.conclusion,attempt:run.run_attempt},jobs:{total:jobs.total_count,executed:executedJobs.map((j:any)=>({name:j.name,labels:j.labels,result:j.conclusion,started:j.started_at,ended:j.completed_at,seconds:(Date.parse(j.completed_at)-Date.parse(j.started_at))/1000,steps:j.steps})),skipped:jobs.jobs.filter((j:any)=>j.conclusion==='skipped').map((j:any)=>j.name)},singleDeployment:mode==='reuse'?executedJobs.length===1&&prepare.steps.filter((s:any)=>s.name.startsWith('Run actions/deploy-pages@')&&s.conclusion==='success').length===1:deploy?.steps.filter((s:any)=>s.name.startsWith('Run actions/deploy-pages@')&&s.conclusion==='success').length===1&&!prepare.steps.some((s:any)=>s.name.startsWith('Run actions/deploy-pages@')&&s.conclusion==='success'),publicFiles,publicRoot:{status:rootResponse.status,url:rootResponse.url,expectedSha256:index.sha256,actualSha256:sha(rootBody),bytes:rootBody.length,matched:rootResponse.status===200&&sha(rootBody)===index.sha256},coverageGaps:['No browser rerun, runtime usability or physical acceptance demonstrated by byte audit.','No real queued multiple-main publication or fault-injected cancellation/deployment failure run.']};
await Bun.write(join(dir,runId+'-verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({runId,mode,inventoryMatches:result.inventoryMatches,exactTree:result.exactTree,singleDeployment:result.singleDeployment,files:files.length,publicExact:publicFiles.every(f=>f.matched)&&result.publicRoot.matched,release,executed:result.jobs.executed.map(j=>({name:j.name,seconds:j.seconds,labels:j.labels}))},null,2));
