import {webkit,devices,expect} from '/Users/tien/Developer/ChronoShift/node_modules/@playwright/test';
const browser=await webkit.launch();const results:any={started:new Date().toISOString(),browser:browser.version(),revision:(await Bun.$`git rev-parse HEAD`.text()).trim(),modes:[]};
for(const mode of ['hover-tab','hover-blur']){
 const context=await browser.newContext({...devices['iPhone 13'],deviceScaleFactor:1,baseURL:'http://127.0.0.1:4262/',locale:'en-AU',timezoneId:'Australia/Sydney'});const page=await context.newPage();
 await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('Manual copy test'))}});const w=window as any;w.events=[];for(const type of ['input','keydown','focus','blur','pointerover'])document.addEventListener(type,e=>{const el=e.target as HTMLElement;if(el?.id==='target-zone'||el?.closest('[data-value="osaka"]'))w.events.push({at:performance.now(),type,key:(e as KeyboardEvent).key,id:el.id,value:(el as HTMLInputElement).value,option:el.closest('[role="option"]')?.getAttribute('data-value'),active:document.querySelector('#target-zone')?.getAttribute('aria-activedescendant')});},true);});
 await page.goto('/');await expect(page.locator('main')).toHaveAttribute('data-offline-ready','true');const target=page.getByLabel('Convert to',{exact:true});
 await target.fill('UTC');await target.press('Tab');await page.getByLabel('Message with a date or time').fill('April 9, 2026 3pm UTC');await expect(page.locator('.hero-time')).toHaveText(/3:00 pm/i);await page.getByRole('button',{name:'Copy UTC',exact:true}).click();await expect(page.getByLabel('Text to copy')).toBeVisible();await target.fill('CST');await target.press('Tab');await expect(page.locator('.result')).toHaveCount(0);await expect(page.getByRole('alert')).toContainText('Choose a timezone');await target.fill('Asia/Tokyo');
 await page.mouse.move(1,1);
 await page.locator('[role="option"][data-value="osaka"]').hover();
 await expect(target).toHaveAttribute('aria-activedescendant',/option-osaka$/);
 const snapshot=async()=>page.evaluate(()=>({value:(document.querySelector('#target-zone') as HTMLInputElement)?.value,expanded:document.querySelector('#target-zone')?.getAttribute('aria-expanded'),active:document.querySelector('#target-zone')?.getAttribute('aria-activedescendant'),options:[...document.querySelectorAll('[role="option"]')].map(o=>({key:o.getAttribute('data-value'),selected:o.getAttribute('aria-selected'),hovered:o.hasAttribute('data-hovered'),focused:o.hasAttribute('data-focused')})),result:document.querySelector('.hero-time')?.textContent,date:document.querySelector('.result-date')?.textContent,source:document.querySelector('.source-label')?.textContent}));
 const before=await snapshot();expect(before.value).toBe('Asia/Tokyo');expect(before.options.find(o=>o.key==='Asia/Tokyo')?.selected).toBe('true');
 if(mode==='hover-tab')await target.press('Tab');else await page.getByLabel('Message with a date or time').click();
 await expect(target).toHaveValue(mode==='hover-tab'?'osaka':'Asia/Tokyo');await expect(page.locator('.hero-time')).toHaveText(/12:00 am/i);await expect(page.locator('.source-label')).toHaveText('UTC');await expect(page.locator('.result-date')).toContainText('10 Apr');
 const after=await snapshot();const events=await page.evaluate(()=>(window as any).events);results.modes.push({mode,before,after,events});await page.screenshot({path:'/tmp/chronoshift-selection-code/'+mode+'.png'});await context.close();
}
await browser.close();results.ended=new Date().toISOString();await Bun.write('/tmp/chronoshift-selection-code/probe.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
