import {chromium,firefox,webkit,devices} from '/Users/tien/Developer/ChronoShift/node_modules/@playwright/test/index.mjs';
import {writeFile} from 'node:fs/promises';
const output='/Users/tien/Developer/ChronoShift/docs/qa/dropdown-alignment-2026-10-05/adversarial-review';
const summaries=[];
for(const [name,type,device] of [['chromium',chromium,{}],['firefox',firefox,{}],['webkit',webkit,{}],['android',chromium,devices['Pixel 7']],['iphone',webkit,devices['iPhone 13']]] as any[]) {
 const browser=await type.launch(); const context=await browser.newContext({...device,viewport:{width:320,height:720},locale:'en-AU',timezoneId:'Australia/Sydney'}); const page=await context.newPage(); const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message)); await page.goto('http://127.0.0.1:4197/'); await page.locator('.appearance summary').click(); await page.locator('#theme').selectOption('light'); await page.locator('.options summary').click(); await page.locator('#message').fill('April 9 2026 at 9am UTC'); await page.locator('#target-zone').fill('Tokyo'); await page.locator('#source-zone').fill('America/Argentina/Buenos_Aires'); await page.locator('#reference-date').fill('2026-04-09'); await page.locator('#date-order').selectOption('dmy'); await page.locator('.convert-button').click(); await page.locator('.hero-time').waitFor(); const before=await page.locator('.result-panel').innerText(); await page.setViewportSize({width:1440,height:900}); await page.locator('#theme').selectOption('dark'); const after=await page.locator('.result-panel').innerText();
 const metrics=await page.evaluate(()=>({userAgent:navigator.userAgent,theme:document.documentElement.dataset.theme,htmlWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,date:(document.querySelector('#reference-date') as HTMLInputElement).value,message:(document.querySelector('#message') as HTMLTextAreaElement).value,controls:[...document.querySelectorAll('input,select,.convert-button')].map(e=>({id:e.id||e.className,rect:e.getBoundingClientRect().toJSON(),padding:getComputedStyle(e).padding}))})); await page.screenshot({path:`${output}/${name}-wide-dark.png`,fullPage:true}); await page.setViewportSize({width:320,height:720}); await page.locator('#theme').selectOption('light'); await page.screenshot({path:`${output}/${name}-320-light.png`,fullPage:true}); const narrow=await page.evaluate(()=>({htmlWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,appearance:document.querySelector('.appearance-fields')!.getBoundingClientRect().toJSON(),longSelect:document.querySelector('#date-order')!.getBoundingClientRect().toJSON()})); let forced;
 if(name==='chromium') { await page.emulateMedia({forcedColors:'active'}); await page.screenshot({path:`${output}/chromium-320-forced-colors.png`,fullPage:true}); forced=await page.evaluate(()=>({active:matchMedia('(forced-colors: active)').matches,choices:[...document.querySelectorAll('.choice-control')].map(e=>({border:getComputedStyle(e.querySelector('input,select')!).borderColor,arrow:getComputedStyle(e,'::after').borderColor,background:getComputedStyle(e.querySelector('input,select')!).backgroundColor}))})); }
 summaries.push({name,version:browser.version(),resultPreserved:before===after,metrics,narrow,forced,errors}); await browser.close();
}
await writeFile(`${output}/independent-probes.json`,JSON.stringify({date:new Date().toISOString(),origin:'http://127.0.0.1:4197/',summaries},null,2)); console.log(JSON.stringify(summaries.map(s=>({name:s.name,version:s.version,preserved:s.resultPreserved,date:s.metrics.date,overflow:s.narrow.scrollWidth-s.narrow.htmlWidth,errors:s.errors})),null,2));
