const raw=await Bun.file(`${import.meta.dir}/raw.json`).json();
const mean=(rows:any[],key:string)=>rows.reduce((sum,row)=>sum+row[key],0)/rows.length;
const stats=(rows:any[])=>({count:rows.length,meanTotalMs:mean(rows,"totalMs"),meanFillMs:mean(rows,"fillMs"),meanObserverWaitMs:mean(rows,"observerWaitMs"),meanAssertionMs:mean(rows,"assertionMs"),meanPostSettleObservationMs:mean(rows,"postSettleObservationMs"),meanPendingToSettledMs:rows.reduce((sum,row)=>sum+row.record.settledAt-row.record.pendingAt,0)/rows.length,totalsMs:rows.map(row=>row.totalMs)});
const profiles=[...new Set<string>(raw.rows.map((row:any)=>row.profile))].map(profile=>{
  const rows=raw.rows.filter((row:any)=>row.profile===profile),A=stats(rows.filter((row:any)=>row.mode==="A")),B=stats(rows.filter((row:any)=>row.mode==="B"));
  return {profile,A,B,meanTotalReductionMs:A.meanTotalMs-B.meanTotalMs,relativeLocalReductionPercent:100*(A.meanTotalMs-B.meanTotalMs)/A.meanTotalMs,blocks:[0,1,2].map(block=>{const group=rows.filter((row:any)=>row.block===block);return {block,order:group.map((row:any)=>row.mode).join(""),meanARowTotalMs:mean(group.filter((row:any)=>row.mode==="A"),"totalMs"),meanBRowTotalMs:mean(group.filter((row:any)=>row.mode==="B"),"totalMs")};})};
});
const out={analyzedAt:new Date().toISOString(),began:raw.began,ended:raw.ended,serverStoppedAt:raw.serverStoppedAt,serverExitCode:raw.serverExitCode,head:raw.head,origin:raw.origin,environment:raw.environment,browsers:raw.browsers,measuredRows:raw.rows.length,errors:raw.errors,assetsStable:raw.assetsStable,allIdentitiesMatch:raw.rows.every((row:any)=>row.record.identity.time===row.expected.time&&row.record.identity.date===row.expected.date&&row.record.identity.zone===row.expected.zone&&row.record.input===row.text&&row.record.settledIdentity.time===row.expected.time),allPendingThenSettled:raw.rows.every((row:any)=>row.record.pendingAt!==null&&row.record.settledAt>row.record.pendingAt),allNormalMotion:raw.rows.every((row:any)=>!row.record.reducedMotion),profiles,verdict:"Useful local observation-delay reduction reproduced; retain as test-only candidate. No complete-suite/Linux/rounded-minute acceptance claim.",limitations:["One serial local ARM process, three repetitions of ABBA per desktop engine; CI viewport/raster matches, concurrency and hardware do not.","Baseline and observer paths both include the same DOM-recording observer and four exact locator assertions. This is an instrumented local comparison, not the unchanged full suite.","postSettleObservationMs includes protocol readback after assertions; no subtraction across clock domains.","Times are sequential new-text conversions with warmed contexts/workers/assets, not independent cold contexts or phone profiles.","Fixed input minute advances by sequence so old ready text cannot satisfy the new assertion; no replay/race/error/partial-result acceptance is established.","Initial zero-row date-oracle setup failure is retained under initial-probe; browser Intl formats a fixed known UTC date as oracle, not app result DOM.","No expected result/zone/input is exported by the production timing reporter; this QA probe deliberately uses saved synthetic text."]};
await Bun.write(`${import.meta.dir}/summary.json`,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
