import { chromium, firefox, webkit, expect } from '/Users/tien/Developer/ChronoShift/node_modules/@playwright/test/index.mjs';
import { writeFile } from 'node:fs/promises';
const origin='http://127.0.0.1:4254';
const start=new Date().toISOString();
const entries:any[]=[]; const errors:any[]=[];
const browser=await chromium.launch();
const context=await browser.newContext({viewport:{width:1280,height:900},timezoneId:'Australia/Sydney',locale:'en-AU',colorScheme:'dark'});
await context.addInitScript(()=>{const Native=window.Worker; (window as any).workerEvents=[]; window.Worker=class extends Native {constructor(...args:any[]){super(...args as [any,any]);(window as any).workerEvents.push({event:'created',at:performance.now()});}terminate(){(window as any).workerEvents.push({event:'terminated',at:performance.now()});super.terminate();}};});
const page=await context.newPage();page.on('pageerror',e=>errors.push({type:'pageerror',text:e.message}));page.on('console',m=>{if(m.type()==='error')errors.push({type:'console',text:m.text()});});page.on('request',r=>{if(!r.url().startsWith(origin))errors.push({type:'offOrigin',url:r.url()});});
await page.goto(origin);await expect(page.locator('main')).toHaveAttribute('data-offline-ready','true');
const draft=page.locator('#message'), target=page.locator('#target-zone'), results=page.locator('.result');
async function result(time:string){await expect(page.locator('.hero-time').first()).toHaveText(time,{timeout:10000});}
async function choice(id:string,value:string){await page.locator('#'+id).click();await page.locator(`.choice-item[data-value="${value}"]`).click();}
async function mark(name:string,data:any={}){entries.push({name,time:new Date().toISOString(),...data});await writeFile('/tmp/chronoshift-live-adversarial/partial-results.json',JSON.stringify({start,entries,errors},null,2));}
await expect(page.getByRole('button',{name:'Convert',exact:true})).toHaveCount(0);
await page.getByText('More options',{exact:true}).click();await choice('time-format','24');await page.getByText('More options',{exact:true}).click();
await target.fill('UTC');await draft.pressSequentially('April 9, 2026 at 3:45pm UTC',{delay:30});await result('15:45');await mark('normal incremental typing', {workers:await page.evaluate(()=>(window as any).workerEvents.length)});
await draft.fill('April 9, 2026 at 9:01:02.345am UTC');await result('09:01:02.345');
// Latest text / settings wins even when prior conversions already started.
await draft.fill('April 9, 2026 at 8am UTC');await page.waitForTimeout(260);await draft.fill('April 9, 2026 at 11pm UTC');await target.fill('Asia/Tokyo');await target.fill('UTC');await result('23:00');await page.waitForTimeout(700);await result('23:00');await mark('rapid text and target ownership');
await page.getByText('More options',{exact:true}).click();const source=page.locator('#source-zone');await source.fill('America/New_York');await draft.fill('April 9, 2026 at 9am');await result('13:00');await source.fill('Asia/Tokyo');await result('00:00');await choice('time-format','12');await result('12:00 am');await choice('time-format','24');await result('00:00');await source.fill('UTC');
await draft.fill('04/09/2026 at 9am UTC');await choice('date-order','mdy');await expect(page.locator('.result-date').first()).toContainText('Apr');await choice('date-order','dmy');await expect(page.locator('.result-date').first()).toContainText('Sept');await mark('source, display and date-order automatically reprocess');
await target.fill('garbage unknown zone');await expect(page.locator('.message.error')).toContainText('Choose a timezone');await expect(results).toHaveCount(0);await target.fill('UTC');await result('09:00');
await draft.fill('   ');await expect(results).toHaveCount(0);await expect(page.locator('.message.error')).toHaveCount(0);await draft.fill('no recognizable timestamp here');await expect(page.locator('.message.error')).toContainText('No timestamp found');await draft.fill('x'.repeat(10001));await expect(page.locator('.message.error')).toContainText('under 10,000');await draft.fill('April 9, 2026 at 5pm UTC');await result('17:00');await page.getByRole('button',{name:'Clear',exact:true}).click();await expect(results).toHaveCount(0);await page.waitForTimeout(700);await expect(results).toHaveCount(0);await mark('invalid/oversize/clear recovery');
// DOM events model IME composition with real React handlers and worker counter.
await draft.fill('April 9, 2026 at 8am UTC');await result('08:00');await draft.dispatchEvent('compositionstart',{data:''});const before=await page.evaluate(()=>(window as any).workerEvents.filter((e:any)=>e.event==='created').length);await draft.fill('April 9, 2026 at 2pm UTC');await page.waitForTimeout(700);await expect(results).toHaveCount(0);expect(await page.evaluate(()=>(window as any).workerEvents.filter((e:any)=>e.event==='created').length)).toBe(before);await draft.dispatchEvent('compositionend',{data:'April 9, 2026 at 2pm UTC'});await result('14:00');await mark('IME waits until composition end');
// Partial reference-date editing must suppress conversion of relative draft.
await draft.fill('Tomorrow at 9am UTC');await result('09:00');const segment=page.locator('[role="spinbutton"]').first();await segment.click();await segment.press('ArrowUp');await expect(page.locator('.message.error')).toContainText('Complete or clear the reference date');await expect(results).toHaveCount(0);await page.getByRole('button',{name:'Choose reference date'}).click();await page.getByRole('button',{name:'Clear reference date'}).click();await result('09:00');await mark('partial reference date blocks and calendar clear recovers');
// Clipboard promise outlasts automatic conversion (which must not conflict).
await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:()=>new Promise(r=>setTimeout(()=>r('April 9, 2026 at 6pm UTC'),850)),writeText:async()=>{}}}));await draft.fill('April 9, 2026 at 1pm UTC');await page.getByRole('button',{name:'Paste',exact:true}).click();await result('13:00');await expect(draft).toHaveValue('April 9, 2026 at 6pm UTC');await result('18:00');await expect(page.locator('.import-choice')).toHaveCount(0);await mark('delayed clipboard import does not conflict with auto conversion');
await page.getByRole('button',{name:'Paste',exact:true}).click();await draft.fill('April 9, 2026 at 7pm UTC');await result('19:00');await expect(page.locator('.import-choice')).toBeVisible();await expect(draft).toHaveValue('April 9, 2026 at 7pm UTC');await page.getByRole('button',{name:'Replace with imported text'}).click();await result('18:00');await mark('delayed clipboard import protects user edit then replace converts');
// Stale copy rejection should not reveal old results after an edit.
await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise((_r,j)=>setTimeout(()=>j(Error('injected clipboard denial')),600)),readText:async()=>''}}));await page.getByRole('button',{name:/^Copy /}).first().click();await draft.fill('April 9, 2026 at 4pm UTC');await result('16:00');await page.waitForTimeout(700);await expect(page.locator('#manual-copy')).toHaveCount(0);await expect(page.locator('.notice')).toHaveText('');await mark('stale copy rejection discarded');
// Inject exactly one worker construction failure; next normal edit recovers.
await page.evaluate(()=>{const Native=window.Worker;let fail=true;window.Worker=class extends Native{constructor(...args:any[]){if(fail){fail=false;throw Error('injected worker start failure');}super(...args as [any,any]);}};});await draft.fill('April 9, 2026 at 2pm UTC');await expect(page.locator('.message.error')).toContainText('could not start conversion');await draft.fill('April 9, 2026 at 3pm UTC');await result('15:00');await mark('worker constructor failure edit recovery');
// Stored update handoff is transient and auto processed on a fresh app mount.
await page.evaluate(()=>sessionStorage.setItem('chronoshift.update-draft',JSON.stringify({text:'April 9, 2026 at 10pm UTC',created:Date.now()})));await page.reload();await result('22:00');expect(await page.evaluate(()=>sessionStorage.getItem('chronoshift.update-draft'))).toBeNull();await mark('update-restored draft auto conversion');
// Share handoff is single use and converts automatically.
await page.evaluate(async()=>{await new Promise<void>((resolve,reject)=>{const r=indexedDB.open('chronoshift-handoff',1);r.onsuccess=()=>{const db=r.result;const tx=db.transaction('messages','readwrite');tx.objectStore('messages').put({text:'April 9, 2026 at 11am UTC',created:Date.now()},'adversarial-share');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};});});await page.goto(origin+'/?share=adversarial-share');await result('11:00');await expect(draft).toHaveValue('April 9, 2026 at 11am UTC');await mark('single-use shared text auto conversion');
await expect(page.locator('main')).toHaveAttribute('data-offline-ready','true');const lifecycle=await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();return {controller:navigator.serviceWorker.controller?.scriptURL,active:r?.active?.state,waiting:r?.waiting?.state,caches:await caches.keys()};});await context.setOffline(true);await page.reload();await draft.fill('April 9, 2026 at 12:34:56.789pm UTC');await result('12:34:56.789');await mark('healthy controlled offline reload and new live input',{lifecycle});await context.setOffline(false);
// Theme and narrow layouts, with long time formats and measured boxes.
await page.getByText('More options',{exact:true}).click();await choice('time-format','12');await result('12:34:56.789 pm');await page.getByText('More options',{exact:true}).click();
for(const theme of ['dark','light']){await page.getByLabel('Appearance',{exact:true}).click();await choice('theme',theme);await page.getByLabel('Appearance',{exact:true}).click();for(const width of [1280,390,280]){await page.setViewportSize({width,height:900});await page.screenshot({path:`/tmp/chronoshift-live-adversarial/${theme}-${width}.png`,fullPage:true});const measure=await page.evaluate(()=>{const rect=(s:string)=>{const e=document.querySelector(s)!;const r=e.getBoundingClientRect();const st=getComputedStyle(e);return {x:r.x,y:r.y,width:r.width,height:r.height,font:st.fontSize,overflow:st.overflowWrap};};return {viewport:innerWidth,scroll:document.documentElement.scrollWidth,workspace:rect('.workspace'),input:rect('.input-panel'),result:rect('.result-panel'),hero:rect('.hero-time'),copy:rect('.copy-button'),source:rect('.result-context'),help:rect('#input-help')};});expect(measure.scroll).toBeLessThanOrEqual(width);await mark(`layout ${theme} ${width}`,{measure});}}
await writeFile('/tmp/chronoshift-live-adversarial/results.json',JSON.stringify({start,end:new Date().toISOString(),browser:browser.version(),entries,errors},null,2));await browser.close();
for(const [name,engine]of [['firefox',firefox],['webkit',webkit]] as const){const b=await engine.launch();const p=await b.newPage({locale:'en-AU',timezoneId:'Australia/Sydney'});await p.goto(origin);await p.locator('#target-zone').fill('UTC');await p.locator('#message').pressSequentially('April 9, 2026 at 9am UTC',{delay:10});await expect(p.locator('.hero-time')).toHaveText('9:00 am');await p.locator('#message').fill('');await expect(p.locator('.result')).toHaveCount(0);console.log(`${name} ${b.version()}: normal typing and immediate clear pass`);await b.close();}
console.log(JSON.stringify({start,end:new Date().toISOString(),entries:entries.length,errors}));
