import {webkit,devices,expect} from '@playwright/test';
import {writeFileSync} from 'node:fs';
const results:any[]=[];
for(const [which,port] of [['before',4276],['prototype',4278]] as const){
 const start=new Date().toISOString();const browser=await webkit.launch();const page=await browser.newPage({...devices['iPhone 13'],deviceScaleFactor:1,locale:'en-AU',timezoneId:'Australia/Sydney'});page.setDefaultTimeout(5000);const consoleLog:any[]=[];page.on('console',m=>{if(m.type()==='error')consoleLog.push({text:m.text(),location:m.location()})});
 await page.addInitScript(()=>{(window as any).__styleEvents=[];(window as any).__csp=[];document.addEventListener('securitypolicyviolation',e=>(window as any).__csp.push({directive:e.effectiveDirective,blocked:e.blockedURI,sample:e.sample,source:e.sourceFile,line:e.lineNumber}));new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n instanceof HTMLStyleElement)(window as any).__styleEvents.push({at:performance.now(),text:n.textContent,nonce:n.nonce});}).observe(document,{childList:true,subtree:true});});
 let error;
 try{await page.goto(`http://127.0.0.1:${port}/`);await page.getByText('More options',{exact:true}).click();const target=page.getByLabel('Convert to',{exact:true});const source=page.getByLabel('Source timezone when none is given',{exact:true});for(const [i,v] of [[source,'UTC'],[target,'UTC']] as const){await i.fill(v);await i.press('Tab')};await page.getByLabel('Message with a date or time').fill('April 9, 2026 3pm UTC');for(const input of [target,source]){await input.fill('CST');await input.press('Tab');await input.fill('Asia/Tokyo');const list=page.locator(`[id="${await input.getAttribute('aria-controls')}"]`);const alias=list.getByRole('option',{name:'Osaka',exact:true});await page.mouse.move(0,0);await alias.hover();await input.press('Tab');await expect(input).toHaveValue('Asia/Tokyo');await input.fill('Asia/Toky');await input.press('ArrowDown');await input.press('End');await expect(alias).toHaveAttribute('data-focused','true');await input.press('Tab');await expect(input).toHaveValue('osaka');await input.fill('Tokyo');await list.getByRole('option',{name:'Tokyo',exact:true}).click();await expect(input).toHaveValue('Asia/Tokyo');}}
 catch(e){error=String(e)}
 const telemetry=await page.evaluate(()=>({csp:(window as any).__csp,styles:(window as any).__styleEvents,liveStyles:[...document.querySelectorAll('style')].map(s=>({text:s.textContent,nonce:s.nonce})),target:(document.querySelector('#target-zone') as HTMLInputElement).value,source:(document.querySelector('#source-zone') as HTMLInputElement).value}));await browser.close();const r={which,port,start,end:new Date().toISOString(),error,consoleLog,telemetry};results.push(r);writeFileSync(`${import.meta.dir}/csp-results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(r));
}
