import {webkit,devices,expect} from '@playwright/test';import {writeFileSync} from 'node:fs';
const results:any[]=[];
for(const [which,port] of [['before',4276],['prototype',4278]] as const)for(let repeat=0;repeat<2;repeat++){
 const start=new Date().toISOString();const browser=await webkit.launch();const page=await browser.newPage({...devices['iPhone 13'],deviceScaleFactor:1,locale:'en-AU',timezoneId:'Australia/Sydney'});page.setDefaultTimeout(5000);const events:any[]=[];page.on('pageerror',e=>events.push({type:'error',message:e.message}));page.on('console',m=>{if(m.type()==='error')events.push({type:'console',message:m.text()})});await page.addInitScript(()=>{(window as any).__csp=[];document.addEventListener('securitypolicyviolation',e=>(window as any).__csp.push({directive:e.effectiveDirective,blocked:e.blockedURI}));});const states:any[]=[];let error;let stage='setup';
 try{await page.goto(`http://127.0.0.1:${port}/`);await page.getByText('More options',{exact:true}).click();for(const label of ['Source timezone when none is given','Convert to']){const i=page.getByLabel(label,{exact:true});await i.fill('UTC');await i.press('Tab');await expect(i).toHaveValue('UTC')};await page.getByLabel('Message with a date or time').fill('April 9, 2026 3pm UTC');
 for(const label of ['Convert to','Source timezone when none is given']){stage=label;const i=page.getByLabel(label,{exact:true});const other=page.getByLabel(label==='Convert to'?'Source timezone when none is given':'Convert to',{exact:true});const before=await other.inputValue();await i.fill('CST');await i.press('Tab');await expect(i).toHaveValue('CST');await i.fill('Asia/Tokyo');await expect(i).toHaveAttribute('aria-controls',/.+/);const list=page.locator(`[id="${await i.getAttribute('aria-controls')}"]`);const alias=list.getByRole('option',{name:'Osaka',exact:true});await page.mouse.move(0,0);await alias.hover();await expect(alias).toHaveAttribute('data-hovered','true');await i.press('Tab');await expect(i).toHaveValue('Asia/Tokyo');await expect(other).toHaveValue(before);await expect(page.getByRole('listbox')).toHaveCount(0);await expect(page.locator('.hero-time')).toHaveText(/12:00 am/i);await expect(page.locator('.result-date')).toContainText('10 Apr');await i.fill('Asia/Toky');await i.press('ArrowDown');await i.press('End');await expect(alias).toHaveAttribute('data-focused','true');await i.press('Tab');await expect(i).toHaveValue('osaka');await expect(page.getByRole('listbox')).toHaveCount(0);
 stage=label+' return focus';await i.scrollIntoViewIfNeeded();await i.click();await expect(i).toBeFocused();await expect(i).toHaveAttribute('aria-expanded','false');states.push({at:new Date().toISOString(),label,beforeFill:{value:await i.inputValue(),expanded:await i.getAttribute('aria-expanded'),scrollY:await page.evaluate(()=>scrollY)}});
 stage=label+' automatic open';await i.fill('Tokyo');await expect(i).toHaveAttribute('aria-expanded','true');await expect(i).toHaveAttribute('aria-controls',/.+/);const fresh=page.locator(`[id="${await i.getAttribute('aria-controls')}"]`);await expect(fresh).toBeVisible();const option=fresh.getByRole('option',{name:'Tokyo',exact:true});await expect(option).toBeVisible();await option.click();await expect(i).toHaveValue('Asia/Tokyo');await expect(other).toHaveValue(before);states.push({at:new Date().toISOString(),label,afterCommit:{value:await i.inputValue(),other:await other.inputValue(),csp:await page.evaluate(()=>(window as any).__csp)}});}}
 catch(e){error=String(e)}await browser.close();const r={which,repeat,start,end:new Date().toISOString(),stage,passed:!error,error,events,states};results.push(r);writeFileSync(`${import.meta.dir}/mobile-preconditions-results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify(r));
}
