import {chromium,webkit,devices,expect} from '@playwright/test';
import {writeFileSync} from 'node:fs';
const results:any[]=[];
for(const [which,port] of [['before',4276],['prototype',4278]] as const)for(const profile of ['chromium','iphone'])for(const journey of ['narrow-resize']){
 const start=new Date().toISOString();const browser=await (profile==='iphone'?webkit:chromium).launch();const page=await browser.newPage({...devices[profile==='iphone'?'iPhone 13':'Desktop Chrome'],deviceScaleFactor:1,...(profile==='chromium'?{viewport:{width:900,height:640}}:{}),locale:'en-AU',timezoneId:'Australia/Sydney'});page.setDefaultTimeout(5000);const states:any[]=[];const logs:any[]=[];page.on('pageerror',e=>logs.push({kind:'error',text:e.message}));page.on('console',m=>{if(m.type()==='error')logs.push({kind:'console',text:m.text()})});
 await page.addInitScript(()=>{(window as any).__csp=[];document.addEventListener('securitypolicyviolation',e=>(window as any).__csp.push({directive:e.effectiveDirective,blocked:e.blockedURI}));});
 const input=page.getByLabel('Convert to',{exact:true});
 const list=()=>page.locator(`[id="${page.getByLabel('Convert to',{exact:true})}"]`);
 async function snap(label:string){states.push({label,at:new Date().toISOString(),data:await page.evaluate(()=>{const i=document.querySelector('#target-zone') as HTMLInputElement;const l=document.getElementById(i.getAttribute('aria-controls')||'');return {value:i.value,focus:document.activeElement?.id,active:i.getAttribute('aria-activedescendant'),list:l?{id:l.id,bounds:l.getBoundingClientRect().toJSON(),scroll:(l as HTMLElement).scrollTop,scrollHeight:l.scrollHeight,n:l.querySelectorAll('[role=option][data-value]').length,options:[...l.querySelectorAll('[role=option][data-value]')].filter(o=>o.getAttribute('data-focused')||o.getBoundingClientRect().top<l.getBoundingClientRect().bottom&&o.getBoundingClientRect().bottom>l.getBoundingClientRect().top).map(o=>({value:o.getAttribute('data-value'),size:o.getAttribute('aria-setsize'),pos:o.getAttribute('aria-posinset'),bounds:o.getBoundingClientRect().toJSON(),focused:o.getAttribute('data-focused')}))}:null,hero:document.querySelector('.hero-time')?.textContent,csp:(window as any).__csp};})});}
 async function owned(){await expect(input).toHaveAttribute('aria-controls',/.+/);return page.locator(`[id="${await input.getAttribute('aria-controls')}"]`)}
 async function open(){await input.fill('');await input.press('Escape');await page.getByRole('button',{name:'Show target timezones',exact:true}).click();await expect(await owned()).toBeVisible();await input.press('ArrowDown')}
 async function active(value:string){await expect.poll(async()=>{const id=await input.getAttribute('aria-activedescendant');return id?await page.locator(`[id="${id}"]`).getAttribute('data-value'):null}).toBe(value);await expect.poll(()=>input.evaluate(i=>{const id=i.getAttribute('aria-activedescendant');const item=document.getElementById(id||'');const box=document.getElementById(i.getAttribute('aria-controls')||'');if(!item||!box)return false;const a=item.getBoundingClientRect(),b=box.getBoundingClientRect();return a.top>=b.top-1&&a.bottom<=b.bottom+1;})).toBe(true);}
 let error;
 try{await page.goto(`http://127.0.0.1:${port}/`);await page.getByLabel('Message with a date or time').fill('April 9, 2026 3pm UTC');await input.fill('UTC');await input.press('Tab');
 if(journey==='end-home'){await open();await snap('opened');await input.press('End');await active('mountain');await snap('End visible owned');await input.press('Home');await active('UTC');await snap('Home visible owned');await input.press('End');await active('mountain');await input.press('Enter');await expect(input).toHaveValue('mountain');await snap('End committed');}
 else if(journey==='narrow-resize'){await page.setViewportSize({width:280,height:960});await input.fill('America/Argentina/Rio_Gallegos');const l=await owned();await expect(l.locator('[role=option][data-value="America/Argentina/Rio_Gallegos"]')).toBeVisible();await snap('wrapped narrow');await page.screenshot({path:`${import.meta.dir}/${which}-${profile}-wrapped.png`});await input.press('Escape');await open();await snap('narrow full');await page.setViewportSize({width:740,height:960});await expect(await owned()).toBeVisible();await snap('resized open');await input.press('End');await active('mountain');await input.press('Enter');await expect(input).toHaveValue('mountain');}
 else if(journey==='empty-offset'){await input.fill('Not/A/Real/Zone');await expect(page.getByText('No matches',{exact:true})).toBeVisible();await expect((await owned()).locator('[role=option][data-value]')).toHaveCount(0);await snap('empty');await input.press('Escape');await input.fill('+05:45');await input.press('Tab');await expect(input).toHaveValue('+05:45');await expect(page.locator('.hero-time')).toHaveText(/8:45 pm/i);await snap('custom');await input.fill('Tokyo');const l=await owned();await l.getByRole('option',{name:'Tokyo',exact:true}).click();await expect(input).toHaveValue('Asia/Tokyo');await expect(page.locator('.hero-time')).toHaveText(/12:00 am/i);await snap('short clicked');}
 else {await open();const l=await owned();await l.hover();await page.mouse.wheel(0,40000);await expect.poll(async()=>{const o=l.locator('[role=option][data-value=mountain]');return await o.count()&&await o.isVisible()}).toBeTruthy();await snap('wheel end');await l.locator('[role=option][data-value=mountain]').click();await expect(input).toHaveValue('mountain');await snap('wheel pointer committed');}
 }catch(e){error=String(e);await snap('failure').catch(()=>{});await page.screenshot({path:`${import.meta.dir}/${which}-${profile}-${journey}-focused-failure.png`}).catch(()=>{});}
 await browser.close();const r={which,profile,journey,start,end:new Date().toISOString(),version:browser.version(),error,passed:!error,states,logs};results.push(r);writeFileSync(`${import.meta.dir}/narrow-results.json`,JSON.stringify(results,null,2));console.log(JSON.stringify({which,profile,journey,passed:!error,error,start,end:r.end}));
}
