import {chromium,firefox,webkit,devices,expect} from "@playwright/test";
const records:any[]=[],start=new Date().toISOString(),orders:Record<string,string[]>={};const save=()=>Bun.write(`${import.meta.dir}/filter-native-results.json`,JSON.stringify({start,end:new Date().toISOString(),records},null,2));
for(const build of [{name:"baseline",port:4321},{name:"candidate",port:4322}])for(const p of [{name:"chromium",engine:chromium,device:"Desktop Chrome",viewport:{width:900,height:640}},{name:"firefox",engine:firefox,device:"Desktop Firefox",viewport:{width:900,height:640}},{name:"iphone",engine:webkit,device:"iPhone 13"}]){const browser=await p.engine.launch(),ctx=await browser.newContext({...devices[p.device],...(p.viewport?{viewport:p.viewport}:{}),deviceScaleFactor:1,locale:"en-AU",timezoneId:"Australia/Sydney",reducedMotion:"no-preference"}),page=await ctx.newPage();page.setDefaultTimeout(5000);const rec:any={build:build.name,profile:p.name,origin:`http://127.0.0.1:${build.port}`,browser:browser.version(),start:new Date().toISOString(),pageErrors:[]};records.push(rec);page.on("pageerror",e=>rec.pageErrors.push(e.message));await page.addInitScript(()=>{(window as any).__csp=[];document.addEventListener('securitypolicyviolation',e=>(window as any).__csp.push({directive:e.effectiveDirective,blocked:e.blockedURI}))});
 try{await page.goto(rec.origin);const input=page.locator('#target-zone');await input.scrollIntoViewIfNeeded();await input.click();await input.fill('');await page.getByRole('button',{name:'Show target timezones',exact:true}).click();await expect(input).toHaveAttribute('aria-expanded','true');await expect(input).toHaveAttribute('aria-controls',/.+/);let list=page.locator(`[id="${await input.getAttribute('aria-controls')}"]`);rec.fullInitialMounted=await list.locator('[role="option"][data-value]').count();
  await input.fill('Argentina');await expect(input).toHaveAttribute('aria-expanded','true');await expect(input).toHaveAttribute('aria-controls',/.+/);list=page.locator(`[id="${await input.getAttribute('aria-controls')}"]`);await expect(list).toBeVisible();if(build.name==='baseline')orders[p.name]=await list.locator('[role="option"][data-value]').evaluateAll(es=>es.map(e=>e.getAttribute('data-value')!));rec.fewLogical=orders[p.name];await input.press('ArrowDown');await input.press('End');await expect.poll(async()=>{const id=await input.getAttribute('aria-activedescendant');return id?list.locator(`[id="${id}"]`).getAttribute('data-value'):null}).toBe(orders[p.name].at(-1));rec.fewLast=orders[p.name].at(-1);
  await input.fill('zzzz-no-timezone-match');await expect(input).toHaveAttribute('aria-expanded','true');list=page.locator(`[id="${await input.getAttribute('aria-controls')}"]`);await expect(list.locator('[role="option"][data-value]')).toHaveCount(0);await expect(list.getByText('No matches',{exact:true})).toBeVisible();await input.fill('');await expect(input).toHaveAttribute('aria-expanded','true');list=page.locator(`[id="${await input.getAttribute('aria-controls')}"]`);await input.press('ArrowDown');await input.press('End');await expect.poll(async()=>{const id=await input.getAttribute('aria-activedescendant');return id?list.locator(`[id="${id}"]`).getAttribute('data-value'):null}).toBe('mountain');await input.press('Enter');await expect(input).toHaveValue('mountain');rec.fullRecovered='mountain';
  await input.scrollIntoViewIfNeeded();await input.click();await input.fill('+05:45');await input.press('Tab');await expect(input).toHaveValue('+05:45');rec.status='pass';
 }catch(e){rec.status='fail';rec.error=String(e);rec.html=await page.locator('body').innerHTML();}finally{rec.csp=await page.evaluate(()=>(window as any).__csp);rec.end=new Date().toISOString();await save();await ctx.close();await browser.close();console.log(JSON.stringify({build:rec.build,profile:rec.profile,status:rec.status,start:rec.start,end:rec.end,error:rec.error}));}
}await save();
