import {chromium,firefox,webkit,devices,expect,type Page,type Locator} from "@playwright/test";
const records:any[]=[],start=new Date().toISOString();const save=()=>Bun.write(`${import.meta.dir}/filter-and-typing-correction-results.json`,JSON.stringify({start,end:new Date().toISOString(),records},null,2));
const orders:Record<string,string[]>={},fewOrders:Record<string,string[]>={};
async function owned(page:Page,input:Locator){await expect(input).toHaveAttribute("aria-expanded","true");const id=await input.getAttribute("aria-controls");expect(id).toBeTruthy();const list=page.locator(`[id="${id}"]`);await expect(list).toBeVisible();return list;}
async function active(page:Page,input:Locator,list:Locator,expected?:string){const observation=expect.poll(async()=>{const id=await input.getAttribute("aria-activedescendant");return id?list.locator(`[id="${id}"]`).getAttribute("data-value"):null});if(expected)await observation.toBe(expected);else await observation.not.toBeNull();const id=await input.getAttribute("aria-activedescendant");const item=list.locator(`[id="${id}"]`);await expect(item).toHaveAttribute("data-focused","true");await expect.poll(()=>item.evaluate(e=>{const r=e.getBoundingClientRect(),b=e.closest('[role="listbox"]')!.getBoundingClientRect();return r.top>=Math.max(0,b.top)-1&&r.bottom<=Math.min(innerHeight,b.bottom)+1})).toBe(true);return item.getAttribute("data-value");}
for(const build of [{name:"baseline",port:4321},{name:"candidate",port:4322}])for(const p of [{name:"chromium",engine:chromium,device:"Desktop Chrome",viewport:{width:900,height:640}},{name:"firefox",engine:firefox,device:"Desktop Firefox",viewport:{width:900,height:640}},{name:"iphone",engine:webkit,device:"iPhone 13"}]){
 const b=await p.engine.launch();for(const journey of ["interior-corrected","full-few-none-full","first-open-tab-typing"]){const rec:any={build:build.name,origin:`http://127.0.0.1:${build.port}`,profile:p.name,browser:b.version(),journey,start:new Date().toISOString()};records.push(rec);const ctx=await b.newContext({...devices[p.device],...(p.viewport?{viewport:p.viewport}:{}),deviceScaleFactor:1,locale:"en-AU",timezoneId:"Australia/Sydney",reducedMotion:"no-preference"}),page=await ctx.newPage();page.setDefaultTimeout(5000);rec.pageErrors=[];page.on("pageerror",e=>rec.pageErrors.push(e.message));await page.addInitScript(()=>{(window as any).__csp=[];document.addEventListener("securitypolicyviolation",e=>(window as any).__csp.push({directive:e.effectiveDirective,blocked:e.blockedURI}))});
 try{await page.goto(rec.origin);const input=page.locator("#target-zone");
 if(journey==="interior-corrected"){
  await input.scrollIntoViewIfNeeded();await input.click();await input.fill("");await page.getByRole("button",{name:"Show target timezones",exact:true}).click();const list=await owned(page,input);if(build.name==="baseline")orders[p.name]=await list.locator('[role="option"][data-value]').evaluateAll(es=>es.map(e=>e.getAttribute('data-value')!));const order=orders[p.name];rec.collection=order;rec.mounted=await list.locator('[role="option"][data-value]').count();rec.interior=[];await input.press("ArrowDown");
  for(const index of [Math.floor(order.length/4),Math.floor(order.length/2),Math.floor(order.length*3/4)]){await input.press("Home");await active(page,input,list,order[0]);for(let i=0;i<index;i++)await input.press("ArrowDown");rec.interior.push({index,value:await active(page,input,list,order[index])});}await input.press("Enter");await expect(input).toHaveValue(order[Math.floor(order.length*3/4)]);
 }else if(journey==="full-few-none-full"){
  await input.scrollIntoViewIfNeeded();await input.click();await input.fill("");await page.getByRole("button",{name:"Show target timezones",exact:true}).click();let list=await owned(page,input);await input.press("ArrowDown");await input.press("End");rec.initialLast=await active(page,input,list);
  await input.fill("Argentina");list=await owned(page,input);if(build.name==="baseline")fewOrders[p.name]=await list.locator('[role="option"][data-value]').evaluateAll(es=>es.map(e=>e.getAttribute('data-value')!));const few=fewOrders[p.name];rec.fewCollection=few;await input.press("ArrowDown");await input.press("End");rec.fewLast=await active(page,input,list,few.at(-1));await input.press("Home");rec.fewFirst=await active(page,input,list,few[0]);
  await input.fill("zzzz-no-timezone-match");list=await owned(page,input);await expect(list.locator('[role="option"][data-value]')).toHaveCount(0);await expect(list.getByText("No matches",{exact:true})).toBeVisible();
  await input.fill("");list=await owned(page,input);await input.press("ArrowDown");await input.press("End");rec.recoveredLast=await active(page,input,list);expect(rec.recoveredLast).toBe(rec.initialLast);await input.press("Enter");await expect(input).toHaveValue(rec.initialLast);
  await input.scrollIntoViewIfNeeded();await input.click();await input.fill("+05:45");await input.press("Tab");await expect(input).toHaveValue("+05:45");
 }else if(journey==="first-open-tab-typing"){
  const summary=page.locator(".options > summary");await expect(page.locator(".options")).not.toHaveAttribute("open","");await summary.focus();await summary.press("Enter");await page.keyboard.press("Tab");await page.keyboard.type("UTC");rec.afterEnter=await page.evaluate(()=>({active:document.activeElement?.id,value:(document.querySelector('#source-zone') as HTMLInputElement)?.value}));expect(rec.afterEnter.active).toBe("source-zone");expect(rec.afterEnter.value).toBe("UTC");await page.keyboard.press("Escape");await summary.focus();await summary.press("Enter");await expect(page.locator(".options")).not.toHaveAttribute("open","");await summary.press("Space");await page.keyboard.press("Tab");await page.keyboard.press("ControlOrMeta+A");await page.keyboard.type("UTC");rec.afterSpace=await page.evaluate(()=>({active:document.activeElement?.id,value:(document.querySelector('#source-zone') as HTMLInputElement)?.value}));expect(rec.afterSpace.active).toBe("source-zone");expect(rec.afterSpace.value).toBe("UTC");
 }else if(journey==="theme-native-tab"){
  await page.getByLabel("Appearance",{exact:true}).click();rec.keys=[];
  for(const key of ["Enter","Space"]){const theme=page.locator("#theme");await theme.focus();await theme.press(key);await expect(page.getByRole("option")).toHaveCount(3);await theme.press("Tab");rec.keys.push({key,afterTab:await page.evaluate(()=>({id:document.activeElement?.id,tag:document.activeElement?.tagName,value:(document.activeElement as HTMLInputElement)?.value})),listboxes:await page.getByRole("listbox").count()});await page.keyboard.press("Escape");}
 }else{
  rec.keys=[];for(const key of ["Enter","Space"]){const toggle=page.getByRole("button",{name:"Show target timezones",exact:true});await input.scrollIntoViewIfNeeded();await input.click();await input.fill("UTC");await input.press("Tab");await expect(page.getByRole("listbox")).toHaveCount(0);await toggle.focus();await toggle.press(key);await owned(page,input);await input.press("Tab");rec.keys.push({key,afterTab:await page.evaluate(()=>({id:document.activeElement?.id,tag:document.activeElement?.tagName}))});await expect(input).toHaveValue("UTC");await expect(page.getByRole("listbox")).toHaveCount(0);await page.keyboard.press("Tab");const activeId=await page.evaluate(()=>document.activeElement?.id);rec.keys.at(-1).afterNextTab=activeId;await input.scrollIntoViewIfNeeded();await input.click();await input.pressSequentially("Tokyo");await expect(input).toHaveValue("UTCTokyo");await input.press("Escape");await input.fill("UTC");await input.press("Tab");}
 }rec.status="pass";
 }catch(e){rec.status="fail";rec.error=String(e);rec.html=await page.locator("body").innerHTML();}finally{rec.csp=await page.evaluate(()=>(window as any).__csp);rec.end=new Date().toISOString();await save();await ctx.close();console.log(JSON.stringify({build:rec.build,profile:rec.profile,journey:rec.journey,status:rec.status,start:rec.start,end:rec.end,error:rec.error}));}
 }await b.close();
}await save();
