import {chromium,firefox,webkit,devices,expect,type Page,type Locator} from "@playwright/test";
const records:any[]=[],start=new Date().toISOString();const save=()=>Bun.write(`${import.meta.dir}/geometry-and-pointer-results.json`,JSON.stringify({start,end:new Date().toISOString(),records},null,2));
async function owned(page:Page,input:Locator){await expect(input).toHaveAttribute("aria-expanded","true");const id=await input.getAttribute("aria-controls");const l=page.locator(`[id="${id}"]`);await expect(l).toBeVisible();return l;}
async function geometry(list:Locator){return list.evaluate(l=>{const b=l.getBoundingClientRect();return{viewport:{w:innerWidth,h:innerHeight},list:{x:b.x,y:b.y,w:b.width,h:b.height,clientWidth:l.clientWidth,scrollWidth:l.scrollWidth,scrollTop:l.scrollTop},rows:[...l.querySelectorAll('[role="option"][data-value]')].map(e=>{const r=e.getBoundingClientRect(),p=e.parentElement!.getBoundingClientRect();return{value:e.getAttribute('data-value'),x:r.x,y:r.y,w:r.width,h:r.height,clientWidth:e.clientWidth,scrollWidth:e.scrollWidth,parentHeight:p.height}})}});}
for(const build of [{name:"baseline",port:4321},{name:"candidate",port:4322}])for(const p of [{name:"chromium",engine:chromium,device:"Desktop Chrome",viewport:{width:900,height:640}},{name:"firefox",engine:firefox,device:"Desktop Firefox",viewport:{width:900,height:640}},{name:"iphone",engine:webkit,device:"iPhone 13"}]){const b=await p.engine.launch();
 for(const journey of ["resize-observed",...(p.name!=="iphone"?["wheel-native-pointer"]:[]),...(p.name==="iphone"?["ancestor-scroll"]:[])]){const rec:any={build:build.name,origin:`http://127.0.0.1:${build.port}`,profile:p.name,browser:b.version(),journey,start:new Date().toISOString(),pageErrors:[],consoleErrors:[]};records.push(rec);const ctx=await b.newContext({...devices[p.device],...(p.viewport?{viewport:p.viewport}:{}),deviceScaleFactor:1,locale:"en-AU",timezoneId:"Australia/Sydney",reducedMotion:"no-preference"}),page=await ctx.newPage();page.setDefaultTimeout(5000);page.on("pageerror",e=>rec.pageErrors.push(e.message));page.on("console",m=>{if(m.type()==="error")rec.consoleErrors.push(m.text())});await page.addInitScript(()=>{(window as any).__csp=[];(window as any).__events=[];document.addEventListener("securitypolicyviolation",e=>(window as any).__csp.push({at:performance.now(),directive:e.effectiveDirective,blocked:e.blockedURI}));for(const name of ["scroll","pointerdown","pointerup"]){document.addEventListener(name,e=>(window as any).__events.push({name,at:performance.now(),id:(e.target as HTMLElement).id,role:(e.target as HTMLElement).getAttribute?.('role'),scrollY}),true)}});
 try{await page.goto(rec.origin);const input=page.locator("#target-zone");await input.scrollIntoViewIfNeeded();await input.click();
  if(journey==="resize-observed"){await input.fill("America/Argentina/Rio_Gallegos");await owned(page,input);rec.geometry=[];
   for(const viewport of [{width:280,height:960},{width:740,height:360},{width:280,height:960}]){await page.setViewportSize(viewport);const list=await owned(page,input);const before=await geometry(list);await expect.poll(async()=>{const g=await geometry(list);return g.list.scrollWidth<=g.list.clientWidth&&g.rows.length>0&&g.rows.every(r=>r.scrollWidth<=r.clientWidth&&r.h>=44&&r.h<=r.parentHeight+1)}).toBe(true);rec.geometry.push({before,after:await geometry(list),utc:new Date().toISOString()});}
   const list=await owned(page,input);await input.press("ArrowDown");await expect.poll(async()=>{const id=await input.getAttribute('aria-activedescendant');return id?list.locator(`[id="${id}"]`).getAttribute('data-value'):null}).toBe("America/Argentina/Rio_Gallegos");await input.press("Enter");await expect(input).toHaveValue("America/Argentina/Rio_Gallegos");rec.cspBeforeScreenshot=await page.evaluate(()=>(window as any).__csp);rec.pageErrorsBeforeScreenshot=[...rec.pageErrors];await input.click();await input.fill("Argentina");await owned(page,input);await page.screenshot({path:`${import.meta.dir}/${build.name}-${p.name}-corrected-narrow.png`});
  }else if(journey==="wheel-native-pointer"){
   await input.fill("");await page.getByRole('button',{name:'Show target timezones',exact:true}).click();const list=await owned(page,input),bounds=(await list.boundingBox())!;await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);const initial=await list.evaluate(l=>l.scrollTop);rec.wheelStart=new Date().toISOString();await page.mouse.wheel(0,620);await expect.poll(()=>list.evaluate(l=>l.scrollTop)).toBeGreaterThan(initial);rec.afterWheel=await geometry(list);
   const visible=rec.afterWheel.rows.find((r:any)=>r.y>=Math.max(0,rec.afterWheel.list.y)&&r.y+r.h<=Math.min(rec.afterWheel.list.y+rec.afterWheel.list.h,p.viewport?.height||664));expect(visible).toBeTruthy();rec.choice=visible;rec.pointerEvents=await list.evaluate(l=>[...l.querySelectorAll('[role="presentation"]')].map(e=>getComputedStyle(e).pointerEvents));rec.pointerStart=new Date().toISOString();await page.mouse.click(visible.x+visible.w/2,visible.y+visible.h/2);rec.pointerEnd=new Date().toISOString();await expect(input).toHaveValue(visible.value);
  }else{await page.getByText('More options',{exact:true}).click();const source=page.locator('#source-zone');await source.scrollIntoViewIfNeeded();await source.click();await source.fill('Argentina');await owned(page,source);rec.beforeScrollY=await page.evaluate(()=>scrollY);await page.evaluate(()=>scrollBy(0,80));await expect.poll(()=>page.evaluate(()=>scrollY)).not.toBe(rec.beforeScrollY);await expect(source).toHaveAttribute('aria-expanded','false');rec.afterScrollY=await page.evaluate(()=>scrollY);await source.scrollIntoViewIfNeeded();await source.click();await source.fill('Tokyo');const list=await owned(page,source);await list.getByRole('option',{name:'Tokyo',exact:true}).click();await expect(source).toHaveValue('Asia/Tokyo');}
  rec.status="pass";
 }catch(e){rec.status="fail";rec.error=String(e);rec.html=await page.locator('body').innerHTML();}finally{rec.csp=await page.evaluate(()=>(window as any).__csp);rec.events=await page.evaluate(()=>(window as any).__events);rec.end=new Date().toISOString();await save();await ctx.close();console.log(JSON.stringify({build:rec.build,profile:rec.profile,journey:rec.journey,status:rec.status,start:rec.start,end:rec.end,error:rec.error}));}
 }await b.close();
}await save();
