import { chromium, expect } from '/Users/tien/Developer/ChronoShift/node_modules/@playwright/test/index.mjs';
const [dir,label]=Bun.argv.slice(2);
const base='/ChronoShift/';
const requests:any[]=[];
const document=await Bun.file(dir+'/index.html').text();
const altered=document.replace("style-src 'self'", "style-src 'self' https://local.adguard.org 'nonce-independent-probe'");
const server=Bun.serve({hostname:'127.0.0.1',port:4241,async fetch(req){const url=new URL(req.url);requests.push({path:url.pathname,search:url.search,mode:req.headers.get('sec-fetch-mode'),at:Date.now()});if(!url.pathname.startsWith(base))return new Response('',{status:404});const path=url.pathname.slice(base.length)||'index.html';if(path==='index.html'&&url.pathname!==base)return new Response(altered,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});const file=Bun.file(dir+'/'+path);if(!await file.exists())return new Response('',{status:404});return new Response(file,{headers:{'Cache-Control':'no-store'}});}});
const browser=await chromium.launch({channel:'chrome'});
const context=await browser.newContext({locale:'en-AU',timezoneId:'Australia/Sydney'});
const page=await context.newPage();const logs:any[]=[];const errors:any[]=[];
page.on('console',m=>logs.push({type:m.type(),text:m.text(),at:Date.now()}));page.on('pageerror',e=>errors.push(e.message));
const started=Date.now();
try{await page.goto('http://127.0.0.1:4241'+base);await page.getByLabel('Message with a date or time').fill('June 18, 2026 at 5:20pm Tokyo');await page.waitForTimeout(16500);const state=await page.evaluate(async()=>({controlled:!!navigator.serviceWorker.controller,ready:document.querySelector('main')?.getAttribute('data-offline-ready'),warning:document.querySelector('.message.warning')?.textContent,caches:await caches.keys(),worker:await navigator.serviceWorker.getRegistration().then(r=>({active:r?.active?.state,waiting:r?.waiting?.state,installing:r?.installing?.state})),draft:(document.querySelector('textarea') as HTMLTextAreaElement)?.value}));const result={label,started:new Date(started).toISOString(),elapsed:Date.now()-started,profile:'fresh installed Google Chrome '+browser.version(),condition:'Root navigation pristine artifact; every direct index.html request (including release query) returns same release HTML with CSP-only inserted proxy-style domain and nonce; no controller initially; real15second deadline',state,requests,logs,errors,originalHash:new Bun.CryptoHasher('sha256').update(document).digest('hex'),alteredHash:new Bun.CryptoHasher('sha256').update(altered).digest('hex')};await Bun.write('/tmp/chronoshift-html-code/'+label+'.json',JSON.stringify(result,null,2));console.log(JSON.stringify({label,elapsed:result.elapsed,profile:result.profile,state,indexRequests:requests.filter(r=>r.path.endsWith('index.html'))},null,2));}finally{await browser.close();server.stop(true);}
