import {chromium,firefox,webkit,devices} from '/Users/tien/Developer/ChronoShift/node_modules/@playwright/test/index.mjs';
import {createHash} from 'node:crypto';
const records:any[]=[];
for(const profile of [{engine:chromium,name:'chromium',options:{viewport:{width:900,height:700}}},{engine:firefox,name:'firefox',options:{viewport:{width:900,height:700}}},{engine:webkit,name:'webkit',options:{viewport:{width:900,height:700}}},{engine:webkit,name:'iphone-emulation',options:devices['iPhone 13']}]){
const b=await profile.engine.launch();const c=await b.newContext({...profile.options,locale:'en-AU',timezoneId:'Australia/Sydney'});const p=await c.newPage();p.setDefaultTimeout(6000);let phase='normal';const consoleErrors:any[]=[];const pageerrors:any[]=[];p.on('console',m=>{if(m.type()==='error')consoleErrors.push({phase,text:m.text()})});p.on('pageerror',e=>pageerrors.push({phase,text:e.message}));await p.addInitScript(()=>{(window as any).violations=[];document.addEventListener('securitypolicyviolation',e=>(window as any).violations.push({directive:e.effectiveDirective,blockedURI:e.blockedURI,sample:e.sample}));});
const start=Date.now();const response=await p.goto('http://127.0.0.1:4204/');const header=response!.headers()['content-security-policy'];await p.getByLabel('Appearance',{exact:true}).click();await p.getByRole('button',{name:/Theme$/}).click();await p.waitForTimeout(150);const modalStyles=await p.locator('head style').allTextContents();await p.locator('[role=option][data-value="light"]').click();await p.getByText('More options',{exact:true}).click();for(const label of ['Numeric dates','Time display']){await p.getByRole('button',{name:new RegExp(label+'$')}).click();await p.waitForTimeout(100);await p.keyboard.press('Escape');}
for(const name of ['Show target timezones','Show source timezones']){await p.getByRole('button',{name}).click();await p.waitForTimeout(100);await p.keyboard.press('Escape');}await p.getByRole('button',{name:'Choose reference date'}).click();await p.waitForTimeout(100);await p.keyboard.press('Escape');await p.waitForTimeout(200);const normalViolations=await p.evaluate(()=>(window as any).violations);const styleInfo=await p.evaluate(()=>Array.from(document.querySelectorAll('head style')).map(s=>({id:s.id,text:s.textContent,sheet:!!s.sheet})));const normalErrors=consoleErrors.filter(e=>e.phase==='normal');
const modalHashes=modalStyles.map(text=>({text,hash:'sha256-'+createHash('sha256').update(text).digest('base64'),inPolicy:header.includes('sha256-'+createHash('sha256').update(text).digest('base64'))}));phase='trusted-style-validation';const trustedContainment=await p.evaluate(()=>{const s=document.createElement('style');s.id='review-trusted-ios-containment';s.textContent='@layer {\n  * {\n    overscroll-behavior: contain;\n  }\n}';document.head.append(s);return {sheet:!!s.sheet,text:s.textContent}});await p.waitForTimeout(100);const trustedStyleViolations=await p.evaluate(()=>(window as any).violations);phase='deliberate-block';await p.evaluate(()=>{(window as any).violations=[];const style=document.createElement('style');style.id='csp-untrusted-style';style.textContent='body { outline: 99px solid magenta !important; }';document.head.append(style);const probe=document.createElement('div');probe.id='csp-untrusted-attribute';probe.setAttribute('style','outline: 98px solid magenta');document.body.append(probe);const script=document.createElement('script');script.textContent='window.__codeReviewerInlineExecuted = true';document.head.append(script);});await p.waitForTimeout(300);const blocked=await p.evaluate(()=>({violations:(window as any).violations,styleSheet:!!(document.getElementById('csp-untrusted-style') as HTMLStyleElement).sheet,bodyOutline:getComputedStyle(document.body).outlineWidth,attributeOutline:getComputedStyle(document.getElementById('csp-untrusted-attribute')!).outlineWidth,scriptRan:'__codeReviewerInlineExecuted' in window,meta:document.querySelector('meta[http-equiv="Content-Security-Policy"]')?.getAttribute('content')}));
records.push({profile:profile.name,version:b.version(),durationMs:Date.now()-start,header,normalViolations,normalErrors,pageerrors,modalHashes,styleInfo,trustedContainment,trustedStyleViolations,blocked});await b.close();}
await Bun.write('/tmp/chronoshift-menu-code/csp-browser.json',JSON.stringify(records,null,2));console.log(JSON.stringify(records,null,2));
