import {chromium,firefox,webkit} from '/Users/tien/Developer/ChronoShift/node_modules/@playwright/test/index.mjs';
const records:any[]=[];
for(const engine of [chromium,firefox,webkit]){
const browser=await engine.launch();const context=await browser.newContext({locale:'en-AU',timezoneId:'Australia/Sydney',viewport:{width:1280,height:900}});const page=await context.newPage();page.setDefaultTimeout(5000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const start=Date.now();
await page.goto('http://127.0.0.1:4211/');await page.locator('#target-zone').fill('Chatham');await page.locator('[role=option][data-value="Pacific/Chatham"]').click();await page.getByRole('button',{name:'Show target timezones'}).click();await page.waitForTimeout(200);const previousArrow={expanded:await page.locator('#target-zone').getAttribute('aria-expanded'),popovers:await page.locator('.choice-popover').count()};await page.screenshot({path:`/tmp/chronoshift-menu-code/${engine.name()}-initial-arrow.png`});
await page.goto('http://127.0.0.1:4204/');await page.locator('#target-zone').fill('UTC');await page.locator('#target-zone').press('Tab');await page.locator('#message').fill('Tomorrow at 3pm');await page.getByText('More options',{exact:true}).click();
for(const [type,value] of [['year','2026'],['month','4'],['day','15']]) {const segment=page.locator(`[data-type="${type}"][role=spinbutton]`);await segment.click();for(const digit of value)await segment.press(digit);await segment.press('Tab');}
const committed=await page.locator('.date-input').innerText();await page.getByRole('button',{name:'Convert',exact:true}).click();await page.locator('.result').first().waitFor();const dated=await page.locator('.result-date').allTextContents();
const day=page.locator('[data-type=day][role=spinbutton]');await day.click();await day.press('Backspace');await day.press('Backspace');await page.getByRole('button',{name:'Convert',exact:true}).click();await page.waitForTimeout(100);const partial={segments:await page.locator('.date-input').innerText(),error:await page.locator('.message.error').allTextContents(),results:await page.locator('.result').count()};
await page.getByRole('button',{name:'Choose reference date'}).click();await page.getByRole('button',{name:'Clear reference date'}).last().click();await page.getByRole('button',{name:'Convert',exact:true}).click();await page.locator('.result').first().waitFor();const automatic={segments:await page.locator('.date-input').innerText(),results:await page.locator('.result').count()};
await page.evaluate(()=>{let resolve:any,reject:any;Object.assign(window,{copyDeferred:new Promise((a,b)=>{resolve=a;reject=b}),copyResolve:()=>resolve(),copyReject:()=>reject(new Error('controlled clipboard denial'))});Object.defineProperty(navigator,'clipboard',{value:{writeText:()=> (window as any).copyDeferred},configurable:true});});await page.getByRole('button',{name:'Copy',exact:false}).first().click();await page.locator('#target-zone').fill('+05:45');await page.locator('#target-zone').press('Tab');await page.evaluate(()=> (window as any).copyReject());await page.waitForTimeout(100);const staleCopy={notice:await page.locator('.notice').innerText(),manual:await page.locator('#manual-copy').count()};
await page.evaluate(()=>{const Original=window.Worker;Object.assign(window,{heldResponse:undefined,postOptions:undefined});window.Worker=class extends Original {set onmessage(callback:any){super.onmessage=(event:any)=>{(window as any).heldResponse=()=>callback(event)};}postMessage(data:any){(window as any).postOptions=data.options;super.postMessage(data)}};});await page.getByRole('button',{name:'Convert',exact:true}).click();await page.waitForFunction(()=>!!(window as any).heldResponse);await page.locator('#source-zone').fill('Asia/Tokyo');await page.locator('#source-zone').press('Tab');await page.evaluate(()=>(window as any).heldResponse());await page.waitForTimeout(100);const staleWorker={busy:await page.getByRole('button',{name:'Convert',exact:true}).getAttribute('aria-busy'),results:await page.locator('.result').count(),postOptions:await page.evaluate(()=>(window as any).postOptions)};
await page.reload();await page.locator('#message').fill('Tomorrow at 3pm');await page.getByRole('button',{name:'Convert',exact:true}).click();await page.locator('.result').first().waitFor();const recovery={results:await page.locator('.result').count(),time:await page.locator('.hero-time').allTextContents()};
records.push({engine:engine.name(),version:browser.version(),durationMs:Date.now()-start,previousArrow,committed,dated,partial,automatic,staleCopy,staleWorker,recovery,errors});await browser.close();}
await Bun.write('/tmp/chronoshift-menu-code/lifecycle.json',JSON.stringify(records,null,2));console.log(JSON.stringify(records,null,2));
