import {createHash} from 'node:crypto';
const root='/tmp/chronoshift-ci-next-delivery/pipeline/fallback';
const began=new Date().toISOString();
const run=await Bun.file(root+'/run.json').json(), jobs=await Bun.file(root+'/jobs.json').json(), artifacts=await Bun.file(root+'/artifacts.json').json();
const raw=await Bun.file(root+'/run.log').text();
const lines=raw.replace(/\u001b\[[0-9;]*m/g,'').replace(/\uFEFF/g,'').split('\n').map(raw=>{const [job,step,...parts]=raw.split('\t');const body=parts.join('\t');const match=body.match(/^([0-9T:.+-]+Z)\s+(.*)$/);return {job,step,at:match?.[1]??null,text:match?.[2]??body,raw};});
// gh emits UNKNOWN STEP for this reusable workflow. Bound by job and actual
// browser inventory header/summary, without relying on unavailable step labels.
const web=lines.filter(l=>l.job==='verify / web');
const begin=web.findIndex(l=>/^Running 273 tests using 4 workers$/.test(l.text)), end=web.findIndex((l,i)=>i>begin && /^\s*264 passed\b/.test(l.text));
if(begin<0 || end<=begin) throw new Error('Browser inventory block absent');
const block=web.slice(begin,end+1);
const rows=block.flatMap(l=>{const m=l.text.match(/^\s*([✓✘×x-])\s+(\d+)\s+\[([^\]]+)\]\s+›\s+(.*?)\s+›\s+(.*)$/);return m?[{at:l.at,symbol:m[1],ordinal:Number(m[2]),project:m[3],location:m[4],title:m[5].replace(/\s+\([\d.]+(?:ms|s)\)$/,''),raw:l.raw}]:[];});
const expected=['firefox','webkit','iphone-emulation'].flatMap(project=>['an activated worker reclaims a hard-refreshed tab without reloading its draft','an explicit update recovers a timed-out readiness probe without another reload','an older active worker cannot mark an uncontrolled tab ready or activate its waiting update'].map(title=>({project,title})));
const key=(r:{project:string,title:string})=>r.project+'|'+r.title;
const skips=rows.filter(r=>r.symbol==='-').map(({project,title})=>({project,title}));
const retryErrors=block.filter(l=>/retry\s*#?\s*[1-9]|^\s*\d+\s+(?:flaky|failed)\b|^\s*(?:Retry|Error:|TimeoutError:)|^\s*[✘×x]\s+\d/i.test(l.text));
const resource=web.flatMap(l=>{const p=l.text.indexOf('[ci-environment]');return p<0?[]:[JSON.parse(l.text.slice(p+'[ci-environment]'.length).trim())];});
const before=resource.find(r=>r.phase==='before'), after=resource.find(r=>r.phase==='after');
const counter=(s:string)=>Object.fromEntries(s.split('\n').map(l=>{const [k,v]=l.split(/\s+/);return [k,Number(v)];}));
const bracketSeconds=(Date.parse(after.at)-Date.parse(before.at))/1000, processorSeconds=(counter(after.cgroup['cpu.stat']).usage_usec-counter(before.cgroup['cpu.stat']).usage_usec)/1e6;
const webJob=jobs.jobs.find((j:any)=>j.name==='verify / web');
const failures:string[]=[];
const require=(ok:boolean,text:string)=>{if(!ok)failures.push(text);};
require(run.id===37301135549 && run.event==='workflow_dispatch' && run.head_sha==='cf4d5b9244278da591a33c1952283e76acb6116c' && run.conclusion==='success' && run.status==='completed','Wrong source/event or incomplete manual success');
require(jobs.total_count===jobs.jobs.length && jobs.jobs.every((j:any)=>j.conclusion==='success'),'Incomplete/failed jobs');
require(rows.length===273 && new Set(rows.map(r=>r.ordinal)).size===273 && rows.every(r=>r.ordinal>=1 && r.ordinal<=273) && new Set(rows.map(key)).size===273,'First-attempt inventory/ordinals mismatch');
require(rows.filter(r=>r.symbol==='✓').length===264 && rows.every(r=>['✓','-'].includes(r.symbol)) && retryErrors.length===0,'Pass/retry/error mismatch');
require(JSON.stringify(expected.map(key).sort())===JSON.stringify(skips.map(key).sort()),'Capability skips changed');
require(web.some(l=>/^\s*116 pass\b/.test(l.text)) && web.some(l=>/^\s*0 fail\b/.test(l.text)),'Unit summaries missing');
const subpathBegin=web.findIndex((l,i)=>i>end && /Running 1 test using 1 worker/.test(l.text));
const subpath=web.slice(subpathBegin).filter(l=>/^\s*1 passed\b/.test(l.text));
require(subpathBegin>end && subpath.length===1,'Separate subpath summary missing');
const required=['Run bun run format:check','Unit tests and production build','Verify the standalone conversion corpus audit','Run bun run test:browser','Verify repository-subpath deployment','Upload the verified Pages build'];
require(required.every(n=>webJob.steps.some((s:any)=>s.name===n && s.conclusion==='success')),'Required full-gate step missing');
const diagnostics=webJob.steps.find((s:any)=>s.name==='Publish failed-attempt diagnostics');
require(diagnostics?.conclusion==='skipped','Failure diagnostic upload ran');
require(artifacts.total_count===artifacts.artifacts.length && artifacts.artifacts.length===1 && artifacts.artifacts[0].name==='github-pages' && !artifacts.artifacts[0].expired,'Unexpected/failure artifacts');
require(Number.isFinite(bracketSeconds) && bracketSeconds>0 && Number.isFinite(processorSeconds) && processorSeconds>=0,'Invalid CPU counters');
require(before.cpuModel==='AMD EPYC 7763 64-Core Processor','Unexpected CPU model');
const ledger=jobs.jobs.map((j:any)=>{const seconds=(Date.parse(j.completed_at)-Date.parse(j.started_at))/1000;return {id:j.id,name:j.name,started_at:j.started_at,completed_at:j.completed_at,conclusion:j.conclusion,seconds,roundedMinutesProxy:Math.ceil(seconds/60),steps:j.steps};});
const ordinary=await Bun.file('/tmp/chronoshift-ci-next-delivery/pipeline/analysis.json').json();
const result={began,ended:new Date().toISOString(),source:run.head_sha,runId:run.id,event:run.event,conclusion:run.conclusion,configured:273,firstAttempts:rows.length,distinctOrdinals:new Set(rows.map(r=>r.ordinal)).size,distinctCases:new Set(rows.map(key)).size,passes:rows.filter(r=>r.symbol==='✓').length,skips,sameCapabilitySkips:true,retryErrors,unknownStepRows:web.filter(l=>l.step==='UNKNOWN STEP').length,browserBlock:{begin:web[begin],end:web[end]},unitSummaries:web.filter(l=>/^\s*(116 pass|0 fail|Ran 116 tests)/.test(l.text)),subpathSummaries:subpath,diagnostics,artifacts,resource:{before,after,bracketSeconds,processorSeconds,averageProcessors:processorSeconds/bracketSeconds},noncausalRunnerComparison:{readyCpuModel:ordinary.resource.before.cpuModel,readyBrowserStepSeconds:ordinary.stepTimes.find((s:any)=>s.name==='Run bun run test:browser').seconds,manualCpuModel:before.cpuModel,manualBrowserStepSeconds:webJob.steps.find((s:any)=>s.name==='Run bun run test:browser').completed_at? (Date.parse(webJob.steps.find((s:any)=>s.name==='Run bun run test:browser').completed_at)-Date.parse(webJob.steps.find((s:any)=>s.name==='Run bun run test:browser').started_at))/1000:null},separateValidationLedger:{jobs:ledger,runnerSeconds:ledger.reduce((s:number,j:any)=>s+j.seconds,0),roundedMinutesProxy:ledger.reduce((s:number,j:any)=>s+j.roundedMinutesProxy,0),ordinaryPairUnchanged:true},failures,limits:['UNKNOWN STEP rows are parsed by job plus the actual Running 273 header/264 passed summary; labels are not invented.','No timing reporter requested; list output supplies first attempts. Successful raw marker files are not uploaded. Marker absence inferred from skipped diagnostics and no failure artifact.','Manual fallback is additional validation cost, not part of the ordinary Web/Pages pair. Per-job API seconds/minute rounding are not billing records.','CPU model differs from ready gate; single samples cannot establish causal CPU-model or source performance effects.','Artifact binary digest/tree/publication audit is owned by root; this audit reads metadata without duplicate binary download or executing artifacts.','Hosted browser results are independently owned by root; no browser checks performed here.']};
await Bun.write(root+'/analysis.json',JSON.stringify(result,null,2)+'\n');
await Bun.write(root+'/browser-attempts.json',JSON.stringify(rows,null,2)+'\n');
console.log(JSON.stringify({failures,attempts:rows.length,passes:result.passes,skips:skips.length,runnerSeconds:result.separateValidationLedger.runnerSeconds,roundedMinutesProxy:result.separateValidationLedger.roundedMinutesProxy,bracketSeconds,processorSeconds,averageProcessors:processorSeconds/bracketSeconds}));
process.exitCode=failures.length?1:0;
