import { chromium, firefox, webkit, devices, expect } from '@playwright/test';
import { resolve, extname } from 'node:path';
import { createHash } from 'node:crypto';
import { PREVIEW_CSP } from '/Users/tien/Developer/ChronoShift/scripts/csp.ts';
const out = '/Users/tien/Developer/ChronoShift/docs/qa/ci-data-zones-2026-10-05/adversarial';
const roots = { baseline: '/tmp/chronoshift-virtualized-zones/baseline-runtime/dist', candidate: '/tmp/chronoshift-data-zones/candidate-runtime/dist' };
const mime = { '.html':'text/html', '.js':'text/javascript', '.css':'text/css', '.svg':'image/svg+xml', '.woff2':'font/woff2', '.webmanifest':'application/manifest+json', '.json':'application/json' };
const report:any = { startedAt:new Date().toISOString(), provenance:'additive after original source navigation dismissals: native source non-navigation boundaries retained; full keyboard navigation separately at tall viewport; no performance conclusion', cases:[], assets:{}, failures:[] };
const servers:any = {};
for (const [name, root] of Object.entries(roots)) {
 const options = { hostname:'127.0.0.1', port:name === 'baseline' ? 4325 : 4326, async fetch(request:Request) { const filePath = resolve(root,new URL(request.url).pathname.slice(1) || 'index.html'); if (!filePath.startsWith(root+'/')) return new Response('Not found',{status:404}); const f=Bun.file(filePath); if (!await f.exists()) return new Response('Not found',{status:404}); return new Response(f,{headers:{'Content-Type':mime[extname(filePath)] || 'application/octet-stream','Content-Security-Policy':PREVIEW_CSP}}); } };
 try { servers[name]=Bun.serve(options); } catch(e) { if ((e as any).code!=='EADDRINUSE') throw e; servers[name]=Bun.serve({...options,port:0}); }
 const files = [...new Bun.Glob('**/*').scanSync({cwd:root,onlyFiles:true})].sort();
 report.assets[name]={origin:`http://127.0.0.1:${servers[name].port}`,root,files:await Promise.all(files.map(async file=>({file,sha256:createHash('sha256').update(new Uint8Array(await Bun.file(root+'/'+file).arrayBuffer())).digest('hex')}))),release:await Bun.file(root+'/release.json').json()};
}
const profiles = [
 {name:'chromium-desktop',type:chromium,options:{viewport:{width:900,height:960},deviceScaleFactor:1}},
 {name:'firefox-desktop',type:firefox,options:{viewport:{width:900,height:960},deviceScaleFactor:1}},
 {name:'webkit-desktop',type:webkit,options:{viewport:{width:900,height:960},deviceScaleFactor:1}},
 {name:'android-native-raster',type:chromium,options:devices['Pixel 7']},
 {name:'iphone-native-raster',type:webkit,options:devices['iPhone 13']},
 {name:'chromium-short',type:chromium,options:{viewport:{width:900,height:640},deviceScaleFactor:1}},
 {name:'chromium-tall-control',type:chromium,options:{viewport:{width:900,height:2400},deviceScaleFactor:1}},
 {name:'firefox-tall-control',type:firefox,options:{viewport:{width:900,height:2400},deviceScaleFactor:1}},
 {name:'webkit-tall-control',type:webkit,options:{viewport:{width:900,height:2400},deviceScaleFactor:1}},
 {name:'chromium-narrow',type:chromium,options:{viewport:{width:280,height:960},deviceScaleFactor:1}},
];
async function save(){await Bun.write(out+'/runtime-observations-addendum.json',JSON.stringify(report,null,2)+'\n');}
async function owned(page:any,input:any){ const id=await input.getAttribute('aria-controls'); expect(id).toBeTruthy(); return page.locator(`[id="${id}"]`); }
async function rows(list:any){ return list.locator('[role=option][data-value]').evaluateAll(elements=>elements.map((el:any)=>({value:el.dataset.value,label:el.querySelector('[slot=label]')?.textContent,description:el.querySelector('[slot=description]')?.textContent??null,position:el.getAttribute('aria-posinset'),size:el.getAttribute('aria-setsize'),labelReference:(el.getAttribute('aria-labelledby')||'').split(' ').filter(Boolean).map(id=>document.getElementById(id)?.textContent??null),descriptionReference:(el.getAttribute('aria-describedby')||'').split(' ').filter(Boolean).map(id=>document.getElementById(id)?.textContent??null),height:el.getBoundingClientRect().height})) ); }
async function snapshot(page:any,input:any){return input.evaluate((el:any)=>{const id=el.getAttribute('aria-activedescendant');const row=id?document.getElementById(id):null;const box=row?.closest('[role=listbox]');const r=row?.getBoundingClientRect(), b=box?.getBoundingClientRect();return {value:el.value,active:id,focusedValue:row?.getAttribute('data-value'),position:row?.getAttribute('aria-posinset'),listHeight:box?.clientHeight,scrollTop:box?.scrollTop,visible:!!r&&!!b&&r.top>=b.top-1&&r.bottom<=b.bottom+1,rowHeight:r?.height,focusId:document.activeElement?.id};});}
try {
 for(const profile of profiles){ const browser=await profile.type.launch(); try {
  for(const [version,asset] of Object.entries(report.assets) as any){
   for(const field of ['target-zone','source-zone']){ const c:any={profile:profile.name,version,field,browserVersion:browser.version(),startedAt:new Date().toISOString(),steps:[],errors:[],consoleErrors:[]};report.cases.push(c);
    const context=await browser.newContext({...profile.options,locale:'en-AU',timezoneId:'Australia/Sydney',reducedMotion:'no-preference'}); const page=await context.newPage(); page.on('pageerror',e=>c.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')c.consoleErrors.push(m.text());});
    await page.addInitScript(()=>{(window as any).__csp=[];document.addEventListener('securitypolicyviolation',(e:any)=>(window as any).__csp.push({directive:e.effectiveDirective,blocked:e.blockedURI}));});
    try {
     await page.goto(asset.origin); const input=page.locator('#'+field);const other=page.locator('#'+(field==='target-zone'?'source-zone':'target-zone'));
     if(field==='source-zone'){const summary=page.locator('.options summary');await summary.click();await page.keyboard.press('Tab');await expect(input).toBeFocused();await page.keyboard.type('UTC');await expect(input).toHaveValue('UTC');c.steps.push({kind:'native-summary-immediate-Tab-type',snapshot:await snapshot(page,input)});await input.press('Escape');}
     await input.scrollIntoViewIfNeeded();await input.click();await input.fill('');await input.press('Escape');await page.getByRole('button',{name:field==='target-zone'?'Show target timezones':'Show source timezones',exact:true}).click();await expect(input).toHaveAttribute('aria-expanded','true');let list=await owned(page,input);await expect.poll(()=>list.locator('[role=option][data-value]').count()).toBeGreaterThan(400);c.fullRows=await rows(list);
     expect(c.fullRows.every(r=>r.height>=44)).toBe(true); expect(new Set(c.fullRows.map(r=>r.value)).size).toBe(c.fullRows.length);
     c.geometry=await list.evaluate((el:any)=>{const pop=el.closest('.choice-popover');const r=pop.getBoundingClientRect();return {width:r.width,height:r.height,x:r.x,y:r.y,listHeight:el.clientHeight,scrollHeight:el.scrollHeight,overflow:pop.scrollWidth>pop.clientWidth,triggerWidth:parseFloat(getComputedStyle(pop).getPropertyValue('--trigger-width'))};});
     for(const key of (profile.name.includes('tall-control')?['Home','ArrowDown','PageDown','PageDown','PageUp','End','Home']:[])){await input.press(key);await expect.poll(async()=>!!(await snapshot(page,input)).focusedValue).toBe(true);const snap=await snapshot(page,input);c.steps.push({kind:'navigation',key,snapshot:snap});expect(snap.visible).toBe(true);if(key==='Home')expect(snap.focusedValue).toBe(c.fullRows[0].value);if(key==='End')expect(snap.focusedValue).toBe(c.fullRows.at(-1).value);}
     await input.press('Escape');const otherBefore=await other.inputValue();await input.scrollIntoViewIfNeeded();await input.click();await input.fill('Asia/Tokyo');list=await owned(page,input);await expect(list).toBeVisible();c.fewRows=await rows(list);await page.mouse.move(0,0);const alias=list.locator('[role=option][data-value="osaka"]');await alias.hover();await expect(alias).toHaveAttribute('data-hovered','true');await input.press('Tab');await expect(input).toHaveValue('Asia/Tokyo');await expect(other).toHaveValue(otherBefore);c.steps.push({kind:'hover-Tab',value:await input.inputValue()});
     await input.scrollIntoViewIfNeeded();await input.click();await input.fill('Asia/Toky');list=await owned(page,input);await input.press('ArrowDown');await input.press('End');await expect(list.locator('[data-value="osaka"]')).toHaveAttribute('data-focused','true');await input.press('Tab');await expect(input).toHaveValue('osaka');await expect(other).toHaveValue(otherBefore);
     await input.scrollIntoViewIfNeeded();await input.click();await input.fill('Definitely/Not-A-Timezone');list=await owned(page,input);await expect(list.getByText('No matches',{exact:true})).toBeVisible();expect(await list.locator('[role=option][data-value]').count()).toBe(0);c.noneRows=await rows(list);await input.press('Escape');await expect(input).toHaveValue('Definitely/Not-A-Timezone');if(field==='target-zone')await expect(input).toHaveAttribute('aria-invalid','true');
     await input.fill('+05:45');await input.press('Escape');await expect(input).toHaveValue('+05:45');if(field==='target-zone')await expect(input).not.toHaveAttribute('aria-invalid','true');
     await input.fill('Tokyo');list=await owned(page,input);await expect(list).toBeVisible();await list.locator('[role=option][data-value="Asia/Tokyo"]').click();await expect(input).toHaveValue('Asia/Tokyo');await expect(other).toHaveValue(otherBefore);
     await page.getByRole('button',{name:field==='target-zone'?'Show target timezones':'Show source timezones',exact:true}).click();list=await owned(page,input);await expect(list).toBeVisible();c.fullRestoredRows=await rows(list);expect(c.fullRestoredRows).toEqual(c.fullRows);
     const beforeWheel=await list.evaluate((el:any)=>el.scrollTop);const b=await list.boundingBox();await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2);await page.mouse.wheel(0,220);await expect.poll(()=>list.evaluate((el:any)=>el.scrollTop)).toBeGreaterThan(beforeWheel);const chosen=await list.locator('[role=option][data-value]').evaluateAll((els:any[])=>{const list=els[0].closest('[role=listbox]').getBoundingClientRect();return els.map(el=>({el,r:el.getBoundingClientRect()})).filter(({r})=>r.top>=list.top&&r.bottom<=list.bottom).map(({el,r})=>({value:el.dataset.value,x:r.left+r.width/2,y:r.top+r.height/2}))[1];});expect(chosen).toBeTruthy();await page.mouse.click(chosen.x,chosen.y);await expect(input).toHaveValue(chosen.value);c.steps.push({kind:'wheel-native-pointer',chosen});
     await page.getByRole('button',{name:field==='target-zone'?'Show target timezones':'Show source timezones',exact:true}).click();await page.setViewportSize({width:280,height:960});if(await input.getAttribute('aria-expanded')!=='true'){c.steps.push({kind:'resize-dismissed'});await input.scrollIntoViewIfNeeded();await page.getByRole('button',{name:field==='target-zone'?'Show target timezones':'Show source timezones',exact:true}).click();}list=await owned(page,input);await expect(list).toBeVisible();c.narrowRows=await rows(list);c.narrowGeometry=await list.evaluate((el:any)=>{const pop=el.closest('.choice-popover');const r=pop.getBoundingClientRect();return {x:r.x,width:r.width,height:r.height,overflow:pop.scrollWidth>pop.clientWidth,viewport:innerWidth};});expect(c.narrowGeometry.x).toBeGreaterThanOrEqual(0);expect(c.narrowGeometry.x+c.narrowGeometry.width).toBeLessThanOrEqual(281);expect(c.narrowGeometry.overflow).toBe(false);
     await input.press('Escape');c.cspBeforeScreenshot=await page.evaluate(()=>(window as any).__csp);expect(c.cspBeforeScreenshot).toEqual([]);expect(c.errors).toEqual([]);expect(c.consoleErrors).toEqual([]);
     await page.screenshot({path:`${out}/addendum-${profile.name}-${version}-${field}.png`}); c.result='passed';
    }catch(e){c.result='failed';c.failure=String(e);report.failures.push({profile:profile.name,version,field,error:String(e)});c.failureTime=new Date().toISOString();c.cspBeforeFailureScreenshot=await page.evaluate(()=>(window as any).__csp).catch(()=>null);await page.screenshot({path:`${out}/ADDENDUM-FAILURE-${profile.name}-${version}-${field}.png`}).catch(()=>{});}finally{c.endedAt=new Date().toISOString();await context.close();await save();}
   }
  }
 }finally{await browser.close();}}
 report.comparisons=[];for(const profile of profiles)for(const field of ['target-zone','source-zone']){const base=report.cases.find(c=>c.profile===profile.name&&c.field===field&&c.version==='baseline');const cand=report.cases.find(c=>c.profile===profile.name&&c.field===field&&c.version==='candidate');const r:any={profile:profile.name,field};for(const key of ['fullRows','fewRows','noneRows','fullRestoredRows','narrowRows']){try{expect(cand[key]).toEqual(base[key]);r[key]='equal';}catch(e){r[key]='different-or-missing';report.failures.push({profile:profile.name,field,comparison:key,error:String(e)});}}report.comparisons.push(r);}
}finally{report.endedAt=new Date().toISOString();await save();for(const s of Object.values(servers) as any[])s.stop(true);}
console.log(JSON.stringify({startedAt:report.startedAt,endedAt:report.endedAt,cases:report.cases.map(({profile,version,field,result,failure})=>({profile,version,field,result,failure})),failures:report.failures},null,2));
