import {strict as assert} from 'node:assert';
const dir='docs/qa/ci-efficiency-2026-10-05/code';
const log=await Bun.file(dir+'/arm-execution.log').text();
function parse(raw:string){
  const rows:any[]=[];for(const line of raw.split('\n')) {
    const parts=line.split('\t');if(parts[1]!=='Run bun run test:browser')continue;
    const text=parts.slice(2).join('\t').replace(/\x1b\[[0-9;]*[A-Za-z]/g,'').replace(/\uFEFF/g,'');
    const m=text.match(/^(\S+Z)\s+([✓✘-])\s+(\d+) \[([^\]]+)\] › (e2e\/[^ ]+:\d+:\d+) › (.*) \(([^)]+)\)$/);if(!m)continue;
    const title=m[6].replace(/ \(retry #\d+\)$/,'');const retry=Number(m[6].match(/retry #(\d+)/)?.[1]||0);
    rows.push({time:m[1],status:m[2]==='✓'?'passed':m[2]==='-'?'skipped':'failed',number:Number(m[3]),project:m[4],location:m[5],title,retry,duration:m[7],key:m[4]+'|'+m[5]+'|'+title});
  }return rows;
}
const attempts=parse(log);assert.equal(attempts.length,258);assert.equal(new Set(attempts.map(x=>x.key)).size,258);assert.equal(attempts.filter(x=>x.status==='passed').length,249);assert.equal(attempts.filter(x=>x.status==='skipped').length,9);assert.equal(attempts.filter(x=>x.retry>0||x.status==='failed').length,0);
const control=parse(await Bun.file('docs/qa/ci-efficiency-2026-10-05/control-linux.log').text());assert.equal(control.length,258);assert.deepEqual(attempts.map(x=>x.key).sort(),control.map(x=>x.key).sort());
const projects=Object.fromEntries([...new Set(attempts.map(x=>x.project))].map(name=>[name,{initial:attempts.filter(x=>x.project===name).length,passed:attempts.filter(x=>x.project===name&&x.status==='passed').length,skipped:attempts.filter(x=>x.project===name&&x.status==='skipped').length}]));
const resources=log.split('\n').filter(x=>x.includes('[ci-environment]')).map(x=>JSON.parse(x.slice(x.indexOf('[ci-environment]')+'[ci-environment]'.length).trim()));assert.equal(resources.length,2);assert.equal(resources[0].architecture,'arm64');assert.equal(resources[1].architecture,'arm64');
const stat=(raw:string)=>Object.fromEntries(raw.split('\n').map(x=>x.trim().split(/\s+/)).map(([a,b])=>[a,Number(b)]));const a=stat(resources[0].cgroup['cpu.stat']),b=stat(resources[1].cgroup['cpu.stat']);
const jobs=await Bun.file(dir+'/arm-execution-jobs.json').json();const run=await Bun.file(dir+'/arm-execution-run.json').json();const artifacts=await Bun.file(dir+'/arm-execution-artifacts.json').json();assert.equal(run.head_sha,'52e8d9c3bc2ba50f6ba2990dde5a128a37849172');assert.equal(run.conclusion,'success');assert.equal(jobs.total_count,jobs.jobs.length);assert.equal(jobs.jobs.length,1);assert.equal(artifacts.total_count,artifacts.artifacts.length);assert.equal(artifacts.artifacts.length,1);assert.equal(artifacts.artifacts[0].name,'github-pages');
const web=jobs.jobs[0];const required=['Run bun run format:check','Unit tests and production build','Verify the standalone conversion corpus audit','Run bun run test:browser','Verify repository-subpath deployment','Upload the verified Pages build'];assert(required.every(name=>web.steps.some((s:any)=>s.name===name&&s.conclusion==='success')));
const sec=(x:string,y:string)=>(Date.parse(y)-Date.parse(x))/1000;const browser=web.steps.find((s:any)=>s.name==='Run bun run test:browser');
const out={at:new Date().toISOString(),run:run.id,head:run.head_sha,attempt:run.run_attempt,job:{id:web.id,start:web.started_at,end:web.completed_at,seconds:sec(web.started_at,web.completed_at),roundedMinutes:Math.ceil(sec(web.started_at,web.completed_at)/60),labels:web.labels},browserStep:{start:browser.started_at,end:browser.completed_at,seconds:sec(browser.started_at,browser.completed_at)},counts:{initial:attempts.length,unique:new Set(attempts.map(x=>x.key)).size,passed:249,skipped:9,retries:0,failures:0},sameIdentitySetAsInstrumentedControl:true,identityHash:new Bun.CryptoHasher('sha256').update(attempts.map(x=>x.key).sort().join('\n')).digest('hex'),projects,cdpCases:attempts.filter(x=>x.project==='foldable'||(x.location.startsWith('e2e/uncontrolled.spec.ts')&&x.status==='passed')),resources,cgroupCpuUsageDeltaUsec:b.usage_usec-a.usage_usec,cgroupCpuThrottledDeltaUsec:b.throttled_usec-a.throttled_usec,cgroupSemantics:'all activity in observed cgroup interval; memory peak includes lifetime/descendants; no effective ancestor-pressure inference',artifact:artifacts.artifacts[0],requiredSteps:required,failedDiagnosticStep:web.steps.find((s:any)=>s.name==='Publish failed-attempt diagnostics'),timingStep:web.steps.find((s:any)=>s.name==='Retain bounded browser timing metadata')};
await Bun.write(dir+'/arm-execution-attempts.json',JSON.stringify(attempts,null,2));await Bun.write(dir+'/arm-execution-summary.json',JSON.stringify(out,null,2));console.log(JSON.stringify({at:out.at,counts:out.counts,projects,job:out.job,browserStep:out.browserStep,identityHash:out.identityHash,cdp:out.cdpCases.length,cpuDeltaUsec:out.cgroupCpuUsageDeltaUsec}));
