import { chromium, webkit, devices, expect } from '@playwright/test';
import { createHash } from 'node:crypto';
const dir='docs/qa/ci-efficiency-2026-10-05/code';
const record:any={began:new Date().toISOString(),platform:process.platform,arch:process.arch,scenarios:[]};
async function state(page:any, input:any){return page.evaluate((id:string)=>{const i=document.getElementById(id)! as HTMLInputElement; const list=document.getElementById(i.getAttribute('aria-controls')||'');const pop=document.querySelector('.choice-popover');const focused=document.getElementById(i.getAttribute('aria-activedescendant')||''); return {value:i.value,expanded:i.getAttribute('aria-expanded'),controls:i.getAttribute('aria-controls'),active:i.getAttribute('aria-activedescendant'),focused:focused?.getAttribute('data-value'),focusConnected:!!focused,scrollY, popup:!!pop,popupHeight:pop?.getBoundingClientRect().height, list:!!list, domOptions:list?.querySelectorAll('[role=option]').length,options:list?[...list.querySelectorAll('[role=option]')].map(o=>({value:o.getAttribute('data-value'),pos:o.getAttribute('aria-posinset'),size:o.getAttribute('aria-setsize'),focused:o.getAttribute('data-focused'),selected:o.getAttribute('aria-selected')})):[]};},await input.getAttribute('id'));}
async function owned(page:any,input:any){const id=await input.getAttribute('aria-controls'); expect(id).toBeTruthy();return page.locator(`[id="${id}"]`);}
for(const profile of ['chromium','webkit','iphone']){
 const browser=await(profile==='chromium'?chromium:webkit).launch();
 for(const candidate of [false,true]){
  const ctx=await browser.newContext({...devices[profile==='iphone'?'iPhone 13':profile==='chromium'?'Desktop Chrome':'Desktop Safari'],locale:'en-AU',timezoneId:'Australia/Sydney'});
  const page=await ctx.newPage();page.setDefaultTimeout(1800); const errors:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{(window as any).violations=[];document.addEventListener('securitypolicyviolation',e=>(window as any).violations.push({directive:e.effectiveDirective,uri:e.blockedURI}));});
  const base=`http://127.0.0.1:${candidate?4278:4276}`;
  const identity={base,release:await(await ctx.request.get(base+'/release.json')).json(),swHash:createHash('sha256').update(await(await ctx.request.get(base+'/sw.js')).text()).digest('hex'),browser:browser.version()};
  async function scenario(name:string,fn:()=>Promise<any>){const r:any={profile,candidate,name,identity,began:new Date().toISOString()};try{r.observations=await fn();r.passed=true;}catch(e){r.passed=false;r.error=String(e);r.failureState=await state(page,page.locator('#target-zone')).catch(()=>null);await page.screenshot({path:`${dir}/virtual-${profile}-${candidate?'candidate':'before'}-${name}.png`}).catch(()=>{});}r.ended=new Date().toISOString();record.scenarios.push(r);console.log(JSON.stringify({profile,candidate,name,passed:r.passed,error:r.error}));await Bun.write(dir+'/virtualization-probe.json',JSON.stringify(record,null,2));}
  await scenario('hover-reopen',async()=>{await page.goto(base);await page.getByText('More options',{exact:true}).click();const target=page.locator('#target-zone'),source=page.locator('#source-zone');await source.fill('UTC');await source.press('Tab');await target.fill('UTC');await target.press('Tab');await page.locator('#message').fill('April 9, 2026 3pm UTC');const observations=[];for(const input of [target,source]){await input.fill('CST');await input.press('Tab');await input.fill('Asia/Tokyo');const list=await owned(page,input),alias=list.getByRole('option',{name:'Osaka',exact:true});await page.mouse.move(0,0);await alias.hover();await expect(alias).toHaveAttribute('data-hovered','true');await input.press('Tab');await expect(input).toHaveValue('Asia/Tokyo');await expect(page.getByRole('listbox')).toHaveCount(0);await input.fill('Asia/Toky');await input.press('ArrowDown');await input.press('End');await expect(alias).toHaveAttribute('data-focused','true');await input.press('Tab');await expect(input).toHaveValue('osaka');await expect(page.getByRole('listbox')).toHaveCount(0);await input.fill('Tokyo');const s=await state(page,input);observations.push({field:await input.getAttribute('id'),afterTokyo:s});await list.getByRole('option',{name:'Tokyo',exact:true}).click();await expect(input).toHaveValue('Asia/Tokyo');}return observations;});
  await scenario('full-keyboard-scroll',async()=>{await page.goto(base);const input=page.locator('#target-zone');await input.fill('');await input.press('Escape');await page.getByRole('button',{name:'Show target timezones',exact:true}).click();const list=await owned(page,input);await expect(list).toBeVisible();const start=await state(page,input);await input.press('End');await expect.poll(async()=>(await state(page,input)).focused).toBeTruthy();const end=await state(page,input);expect(end.focusConnected).toBe(true);await input.press('Home');const home=await state(page,input);expect(home.focused).toBe('UTC');await input.press('ArrowDown');const down=await state(page,input);expect(down.focused).not.toBe('UTC');await input.press('Enter');await expect(input).toHaveValue(down.focused);await page.getByRole('button',{name:'Show target timezones',exact:true}).click();const list2=await owned(page,input);await list2.evaluate((el:any)=>el.scrollTop=el.scrollHeight);await expect.poll(async()=>await list2.locator('[role=option]').last().getAttribute('aria-posinset')).toBe(candidate?(profile==='chromium'?'454':'479'):null);const last=await list2.locator('[role=option]').last().getAttribute('data-value');await list2.locator('[role=option]').last().click();await expect(input).toHaveValue(last);return{start,end,home,down,last,selected:await state(page,input)};});
  await scenario('filter-wrap-resize',async()=>{await page.goto(base);await page.setViewportSize({width:280,height:960});const input=page.locator('#target-zone');await input.fill('Definitely/Not-A-Timezone');await expect(page.getByText('No matches',{exact:true})).toBeVisible();await expect(page.getByRole('option')).toHaveCount(0);await input.fill('+05:45');await input.press('Escape');await expect(input).toHaveValue('+05:45');await input.fill('Argentina');const list=await owned(page,input);await expect(list.getByRole('option').first()).toBeVisible();const sizes=await list.getByRole('option').evaluateAll((nodes:any[])=>nodes.map(n=>({value:n.getAttribute('data-value'),bounds:{x:n.getBoundingClientRect().x,y:n.getBoundingClientRect().y,width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height},overflow:n.scrollWidth>n.clientWidth,label:n.querySelector('[slot=label]')?.textContent,desc:n.querySelector('[slot=description]')?.textContent})));expect(sizes.every(s=>!s.overflow)).toBe(true);const pop=page.locator('.choice-popover:visible');const bounds=(await pop.boundingBox())!;expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(281);await page.setViewportSize({width:740,height:360});await expect(pop).toBeVisible();await page.setViewportSize({width:280,height:960});await input.press('End');const end=await state(page,input);expect(end.focusConnected).toBe(true);await input.press('Tab');await expect(input).toHaveValue(end.focused);return{sizes,end,bounds,violations:await page.evaluate(()=>(window as any).violations)};});
  record.scenarios.push({profile,candidate,name:'console-csp',errors,violations:await page.evaluate(()=>(window as any).violations),passed:errors.length===0});
  await ctx.close();
 }
 await browser.close();
}
record.ended=new Date().toISOString();await Bun.write(dir+'/virtualization-probe.json',JSON.stringify(record,null,2));
