import { chromium,expect } from '@playwright/test';
import {createHash} from 'node:crypto';
const out='/tmp/chronoshift-menu-hosted-existing',url='https://tien-lam.github.io/ChronoShift/';
const started=Date.now(),browser=await chromium.launch();const context=await browser.newContext({locale:'en-AU',timezoneId:'Australia/Sydney',viewport:{width:1280,height:900}});
let page=await context.newPage();const diagnostics:any[]=[];
function observe(){page.on('pageerror',e=>diagnostics.push({t:Date.now()-started,type:'pageerror',message:e.message}));page.on('console',m=>{if(m.type()==='error')diagnostics.push({t:Date.now()-started,type:'console',message:m.text()});});}
observe();const report:any={started:new Date(started).toISOString(),browser:browser.version(),profile:'disposable Chromium desktop en-AU Australia/Sydney',gaps:'No physical device, installed OS integration, actual screen reader/zoom/phone performance; no rollback or redeployment',stages:[],diagnostics};
const save=()=>Bun.write(out+'/report.json',JSON.stringify(report,null,2));
async function identity(){return await page.evaluate(async()=>({release:await(await fetch('release.json')).json(),controller:navigator.serviceWorker.controller?.scriptURL,assets:[...document.querySelectorAll('script[src],link[rel=stylesheet]')].map(n=>n.getAttribute('src')||n.getAttribute('href')),theme:document.documentElement.dataset.theme,target:(document.querySelector('#target-zone')as HTMLInputElement).value}));}
async function assets(){const ids=await identity(),result=[];for(const a of ids.assets){const r=await page.evaluate(async(a)=>[...new Uint8Array(await(await fetch(a!)).arrayBuffer())],a);result.push({asset:a,sha256:createHash('sha256').update(new Uint8Array(r)).digest('hex')});}return {...ids,hashes:result};}
try{
 await page.goto(url);await expect(page.locator('main[data-offline-ready=true]')).toBeVisible({timeout:30000});await page.locator('#target-zone').fill('UTC');await page.locator('#target-zone').press('Tab');await page.locator('.appearance summary').click();await page.locator('#theme').selectOption('light');await page.locator('.appearance summary').click();
 const draft='April 9, 2026 3pm in Tokyo';await page.locator('#message').fill(draft);await page.getByRole('button',{name:'Convert',exact:true}).click();await expect(page.locator('.hero-time')).toContainText('6:00 am');
 report.baseline={...(await assets()),readyMs:Date.now()-started,text:await page.locator('#message').inputValue(),result:await page.locator('.result').textContent(),caches:await page.evaluate(()=>caches.keys())};await save();console.log('BASELINE READY '+JSON.stringify(report.baseline));
 let command:any;
 while(!command){if(await Bun.file(out+'/publish.json').exists()){const c=await Bun.file(out+'/publish.json').json();if(/^[a-f0-9]{40}$/.test(c.sourceCommit))command=c;}if(!command)await Bun.sleep(1000);}
 const noticed=Date.now(),expected=command.sourceCommit;report.expected=expected;
 await expect.poll(async()=> (await(await context.request.get(url+'release.json')).json()).sourceCommit,{timeout:120000,intervals:[2000]}).toBe(expected);
 expect((await identity()).release.sourceCommit).toBe(report.baseline.release.sourceCommit);await expect(page.locator('#message')).toHaveValue(draft);await expect(page.locator('.hero-time')).toContainText('6:00 am');
 await page.evaluate(async()=>{await(await navigator.serviceWorker.getRegistration())!.update();});await expect(page.getByRole('button',{name:'Update now',exact:true})).toBeVisible({timeout:30000});
 const waiting=await identity();expect(waiting.release.sourceCommit).toBe(report.baseline.release.sourceCommit);await expect(page.locator('#target-zone')).toHaveValue('UTC');expect(waiting.theme).toBe('light');report.stages.push({stage:'waiting-explicit-update',elapsedMs:Date.now()-started,sinceNotificationMs:Date.now()-noticed,identity:waiting,text:await page.locator('#message').inputValue(),result:await page.locator('.result').textContent()});await save();
 await Promise.all([page.waitForEvent('domcontentloaded'),page.getByRole('button',{name:'Update now',exact:true}).click()]);await expect(page.locator('#message')).toHaveValue(draft,{timeout:30000});await expect(page.locator('main[data-offline-ready=true]')).toBeVisible();expect((await identity()).release.sourceCommit).toBe(expected);await expect(page.locator('#target-zone')).toHaveValue('UTC');expect(await page.locator('html').getAttribute('data-theme')).toBe('light');
 await page.locator('.appearance summary').click();await page.locator('#theme').click();await expect(page.locator('.choice-popover')).toBeVisible();await expect(page.locator('.choice-item[data-value=light]')).toHaveAttribute('aria-selected','true');await page.keyboard.press('Escape');await page.locator('.appearance summary').click();await page.locator('.options summary').click();
 for(const id of ['date-order','time-format']){await page.locator('#'+id).click();await expect(page.locator('.choice-popover')).toBeVisible();await page.keyboard.press('Escape');}
 await page.getByRole('button',{name:'Show target timezones',exact:true}).click();await expect(page.locator('.choice-popover')).toBeVisible();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Show source timezones',exact:true}).click();await expect(page.locator('.choice-popover')).toBeVisible();await page.keyboard.press('Escape');
 await page.locator('.date-choice-calendar-button').click();await expect(page.locator('.calendar-popover')).toBeVisible();await page.locator('.calendar-day').filter({hasText:/^20$/}).first().click();await page.locator('#target-zone').fill('+05:45');await page.locator('#target-zone').press('Tab');await page.getByRole('button',{name:'Convert',exact:true}).click();await expect(page.locator('.hero-time')).toContainText('11:45 am');
 report.stages.push({stage:'explicit-update-and-all-six-menus',elapsedMs:Date.now()-started,identity:await assets(),text:await page.locator('#message').inputValue(),result:await page.locator('.result').textContent(),preferences:await page.evaluate(()=>localStorage.getItem('chronoshift.preferences.v1'))});await save();
 await page.locator('#target-zone').fill('UTC');await page.locator('#target-zone').press('Tab');await page.close();await context.setOffline(true);page=await context.newPage();observe();await page.goto(url);await expect(page.locator('main[data-offline-ready=true]')).toBeVisible();await expect(page.locator('#target-zone')).toHaveValue('UTC');expect(await page.locator('html').getAttribute('data-theme')).toBe('light');await page.locator('#message').fill('July 15, 2026 9am in Tokyo');await page.getByRole('button',{name:'Convert',exact:true}).click();await expect(page.locator('.hero-time')).toContainText('12:00 am');expect((await identity()).release.sourceCommit).toBe(expected);await page.getByRole('button',{name:'Show target timezones',exact:true}).click();await expect(page.locator('.choice-popover')).toBeVisible();await page.keyboard.press('Escape');
 report.stages.push({stage:'offline-close-reopen-fresh-conversion',elapsedMs:Date.now()-started,identity:await assets(),text:await page.locator('#message').inputValue(),result:await page.locator('.result').textContent(),draftAbsentFromPreferences:!(await page.evaluate(()=>localStorage.getItem('chronoshift.preferences.v1')))?.includes('July')});expect(diagnostics).toEqual([]);report.finished=new Date().toISOString();await save();console.log('HOSTED EXISTING CLIENT COMPLETE '+JSON.stringify(report));
}catch(e){report.failure={message:String(e),elapsedMs:Date.now()-started};await save();console.log('FAILED '+String(e));throw e;}finally{await browser.close();}
