package com.chronoshift.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFCFBCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Teal80 = Color(0xFF80D8C4)

val Purple40 = Color(0xFF6750A4)
val PurpleGrey40 = Color(0xFF625B71)
val Teal40 = Color(0xFF00796B)

val LightPrimary = Color(0xFF4A5FC1)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDEE0FF)
val LightOnPrimaryContainer = Color(0xFF00105C)
val LightSecondary = Color(0xFF5B5D72)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE0E0F9)
val LightOnSecondaryContainer = Color(0xFF181A2C)
val LightTertiary = Color(0xFF00796B)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFB2DFDB)
val LightOnTertiaryContainer = Color(0xFF00201C)
val LightBackground = Color(0xFFFCFCFF)
val LightOnBackground = Color(0xFF1B1B1F)
val LightSurface = Color(0xFFFCFCFF)
val LightOnSurface = Color(0xFF1B1B1F)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

val DarkPrimary = Color(0xFFBBC3FF)
val DarkOnPrimary = Color(0xFF132278)
val DarkPrimaryContainer = Color(0xFF2F3F90)
val DarkOnPrimaryContainer = Color(0xFFDEE0FF)
val DarkSecondary = Color(0xFFC4C5DD)
val DarkOnSecondary = Color(0xFF2D2F42)
val DarkSecondaryContainer = Color(0xFF434559)
val DarkOnSecondaryContainer = Color(0xFFE0E0F9)
val DarkTertiary = Color(0xFF80CBC4)
val DarkOnTertiary = Color(0xFF003732)
val DarkTertiaryContainer = Color(0xFF00504A)
val DarkOnTertiaryContainer = Color(0xFFB2DFDB)
val DarkBackground = Color(0xFF1B1B1F)
val DarkOnBackground = Color(0xFFE4E1E6)
val DarkSurface = Color(0xFF1B1B1F)
val DarkOnSurface = Color(0xFFE4E1E6)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
