import {chromium} from '/Users/tien/Developer/ChronoShift/node_modules/playwright/index.mjs';
const baseline='/tmp/chronoshift-uncontrolled-adversarial-baseline-dist',candidate='/tmp/chronoshift-uncontrolled-adversarial-candidate-dist',served='/tmp/chronoshift-uncontrolled-adversarial-dist';
async function publish(root:string){await Bun.spawn(['mv','-f',served,served+'-retained-'+Date.now()]).exited;await Bun.spawn(['cp','-rf',root,served]).exited;}
await publish(baseline);const browser=await chromium.launch({channel:'chrome',headless:true});const ctx=await browser.newContext();await ctx.addInitScript(()=>sessionStorage.setItem('chronoshift-detailed-logs','true'));const page=await ctx.newPage();const cdp=await ctx.newCDPSession(page);const logs:any[]=[];const errors:any[]=[];let diagnosticContextLoss=0;page.on('console',async m=>{if(m.type()==='error')errors.push(m.text());if(m.text().startsWith('[ChronoShift]')){try{logs.push({message:m.text(),fields:await m.args()[1]?.jsonValue()})}catch{diagnosticContextLoss++}}});page.on('pageerror',e=>errors.push(e.message));let navigations=0;page.on('framenavigated',f=>{if(f===page.mainFrame())navigations++});
const results:any={browser:browser.version(),baseline:JSON.parse(await Bun.file(`${baseline}/release.json`).text()),candidate:JSON.parse(await Bun.file(`${candidate}/release.json`).text())};
async function snap(){return await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();return {at:performance.now(),controller:navigator.serviceWorker.controller?.state||null,active:r?.active?.state,waiting:r?.waiting?.state,installing:r?.installing?.state,ready:document.querySelector('main')?.getAttribute('data-offline-ready'),warning:[...document.querySelectorAll('.message.warning')].map(x=>x.textContent),update:!!document.querySelector('.update-banner')}})}
await page.goto('http://127.0.0.1:4244/ChronoShift/');await page.waitForFunction(()=>document.querySelector('main')?.getAttribute('data-offline-ready')==='true');const oldAsset=await page.evaluate(()=>[...document.scripts].find(x=>x.src.includes('/assets/index-'))?.src);await publish(candidate);results.oldRuntimeNetworkStatus=(await ctx.request.get(oldAsset!)).status();
await cdp.send('Page.reload',{ignoreCache:true});await page.waitForTimeout(1000);await page.getByLabel('Message with a date or time').fill('June 18, 2026 at 5:20pm Tokyo');await page.getByLabel('Convert to',{exact:true}).fill('Europe/London');await page.getByLabel('Convert to',{exact:true}).press('Tab');await page.getByRole('button',{name:'Convert',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.hero-time')?.textContent==='9:20');await page.waitForTimeout(17000);
results.beforeAction={snapshot:await snap(),navigations,input:await page.getByLabel('Message with a date or time').inputValue(),result:await page.locator('.hero-time').textContent()};await page.screenshot({path:'/tmp/chronoshift-uncontrolled-adversarial-transition-before-action.png',fullPage:true});
await page.getByRole('button',{name:'Update now',exact:true}).click();await page.waitForFunction(()=>document.querySelector('main')?.getAttribute('data-offline-ready')==='true');await page.waitForTimeout(200);results.afterExplicitAction={snapshot:await snap(),navigations,input:await page.getByLabel('Message with a date or time').inputValue()};await page.waitForFunction(()=>document.querySelector('main')?.getAttribute('data-offline-ready')==='true');
await cdp.send('Page.reload',{ignoreCache:true});await page.waitForTimeout(17000);results.candidateHardRefresh={snapshot:await snap(),navigations};await page.close();await ctx.setOffline(true);const reopen=await ctx.newPage();await reopen.goto('http://127.0.0.1:4244/ChronoShift/');await reopen.waitForFunction(()=>document.querySelector('main')?.getAttribute('data-offline-ready')==='true');await reopen.getByLabel('Message with a date or time').fill('June 18, 2026 at 5:20pm Tokyo');await reopen.getByLabel('Convert to',{exact:true}).fill('Europe/London');await reopen.getByLabel('Convert to',{exact:true}).press('Tab');await reopen.getByRole('button',{name:'Convert',exact:true}).click();await reopen.waitForFunction(()=>document.querySelector('.hero-time')?.textContent==='9:20');results.offlineReopen={ready:await reopen.locator('main').getAttribute('data-offline-ready'),conversion:await reopen.locator('.hero-time').textContent()};results.errors=errors;results.diagnosticContextLoss=diagnosticContextLoss;results.logs=logs;await Bun.write('/tmp/chronoshift-uncontrolled-adversarial-transition-after.json',JSON.stringify(results,null,2));console.log(JSON.stringify({browser:results.browser,beforeAction:results.beforeAction,afterExplicitAction:results.afterExplicitAction,candidateHardRefresh:results.candidateHardRefresh,offlineReopen:results.offlineReopen,oldRuntimeNetworkStatus:results.oldRuntimeNetworkStatus},null,2));await browser.close();
